wsl = false
no-multigrid = false
vsync = true
maximized = false
srgb = false
idle = true
frame = "none"
title-hidden = true
tabs = false

[font]
normal = { family = "Iosevka", style = "Regular" }
bold = { family = "Iosevka", style = "Bold" }
italic = { family = "Iosevka", style = "Italic" }
bold_italic = { family = "Iosevka", style = "BoldItalic" }
size = 16

[font.features]
IosevkaTermNFM = [ "calt=1", "clig=1", "liga=1", "dlig=1", "cv26=12", "cv85=6", "+ss10" ]
