# 8. Carbonfox
[colors.primary]
background = "#161616"
foreground = "#F2F4F8"
[colors.normal]
black   = "#282828"
red     = "#EE5396"
green   = "#25BE6A"
yellow  = "#08BDBA"
blue    = "#78A9FF"
magenta = "#BE95FF"
cyan    = "#33B1FF"
white   = "#DFDFE0"
[colors.bright]
black   = "#484848"
red     = "#F16DA6"
green   = "#46C880"
yellow  = "#2DC7C4"
blue    = "#8CB6FF"
magenta = "#C8A5FF"
cyan    = "#52BDFF"
white   = "#E4E4E5"
[colors.indexed_colors]
{ index  16, color = "#3DDBD9" }
{ index  17, color = "#FF7EB6" }

