# 13. Oxocarbon
[colors.primary]
background = "#161616"
foreground = "#ffffff"
[colors.cursor]
text    = "CellBackground"
cursor  = "#528BFF"
[colors.search]
matches  = { foreground = "CellBackground", background = "#ee5396" }
[colors.footer_bar]
background = "#262626"
foreground = "#ffffff"
[colors.normal]
black = "#262626"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#dde1e6"
[colors.bright]
black = "#393939"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#ffffff"
