# 6. Tokyo Night Moon
[colors.primary]
background = "#222436"
foreground = "#C8D3F5"
[colors.cursor]
text   = "CellBackground"
cursor = "#528BFF"
[colors.search]
matches       = { foreground = "#44475A", background = "#50FA7B" }
focused_match = { foreground = "#44475A", background = "#FFB86C" }
[colors.footer_bar]
background = "#282A36"
foreground = "#F8F8F2"
[colors.normal]
black   = "#1B1D2B"
red     = "#FF757F"
green   = "#C3E88D"
yellow  = "#FFC777"
blue    = "#82AAFF"
magenta = "#C099FF"
cyan    = "#86E1FC"
white   = "#828BB8"
[colors.bright]
black   = "#444A73"
red     = "#FF757F"
green   = "#C3E88D"
yellow  = "#FFC777"
blue    = "#82AAFF"
magenta = "#C099FF"
cyan    = "#86E1FC"
white   = "#C8D3F5"
[colors.indexed_colors]
{ index = 16, color = "#FF966C" }
{ index = 17, color = "#C53B53" }

