;;; mfd.el --- Monotone MFD/CRT theme engine -*- lexical-binding: t; -*-
;;; Commentary:
;;; Code:

(require 'cl-lib)

(defgroup mfd nil "Monotone MFD/CRT theme family." :group 'faces :prefix "mfd-")

(defcustom mfd-accessibility-contrast 0
  "WCAG contrast level (0-10) evaluated solely at theme load."
  :type '(integer :tag "0-10") :group 'mfd)

(defcustom mfd-no-italic nil
  "Strip italic slant at load time."
  :type 'boolean :group 'mfd)

(defcustom mfd-terminal-cursor-sync t
  "Emit OSC 12 sequence on load."
  :type 'boolean :group 'mfd)

(defvar mfd-palettes
  '((mfd        . ((bg . "#7A8B69") (fg . "#1E2D1E") (dim . "#5A6B4A") (bright . "#0D1D0D") (subtle . "#687858") (visual . "#6A7B59") (cursor . "#848F72") (border . "#5A6B4A") (float_bg . "#5A6B4A")))
    (mfd-dark   . ((bg . "#1E2D1E") (fg . "#8A9B70") (dim . "#3A4A3A") (bright . "#A0B180") (subtle . "#2E3E2E") (visual . "#2A3D2A") (cursor . "#253525") (border . "#3A4B2A") (float_bg . "#253525")))
    (mfd-stealth . ((bg . "#0D1410") (fg . "#7A9A7A") (dim . "#253828") (bright . "#9ABB9A") (subtle . "#2A3A2A") (visual . "#1A2A1A") (cursor . "#151F18") (border . "#2A3A2A") (float_bg . "#101810")))
    (mfd-mono   . ((bg . "#08080C") (fg . "#D0D0D8") (dim . "#282830") (bright . "#F0F0FF") (subtle . "#383840") (visual . "#1A1A22") (cursor . "#101014") (border . "#2A2A32") (float_bg . "#0C0C10")))
    (mfd-flir   . ((bg . "#181818") (fg . "#909090") (dim . "#404040") (bright . "#A8A8A8") (subtle . "#2E2E2E") (visual . "#242424") (cursor . "#202020") (border . "#2E2E2E") (float_bg . "#1C1C1C")))
    (mfd-paper  . ((bg . "#BBC5B7") (fg . "#002611") (dim . "#8A9A88") (bright . "#001008") (subtle . "#A5B2A2") (visual . "#A0B0A0") (cursor . "#B0BAB0") (border . "#95A592") (float_bg . "#C5CFC2")))))

(defun mfd--hex-to-rgb (hex)
  (list (/ (string-to-number (substring hex 1 3) 16) 255.0)
        (/ (string-to-number (substring hex 3 5) 16) 255.0)
        (/ (string-to-number (substring hex 5 7) 16) 255.0)))

(defun mfd--rgb-to-hex (r g b)
  (format "#%02X%02X%02X"
          (max 0 (min 255 (round (* r 255))))
          (max 0 (min 255 (round (* g 255))))
          (max 0 (min 255 (round (* b 255))))))

(defun mfd--rgb-to-hsv (r g b)
  (let* ((mx (max r g b)) (mn (min r g b)) (d (- mx mn))
         (s (if (> mx 0) (/ d mx) 0)) (h 0))
    (when (> d 0)
      (setq h (cond ((= mx r) (mod (/ (- g b) d) 6.0))
                    ((= mx g) (+ (/ (- b r) d) 2.0))
                    (t (+ (/ (- r g) d) 4.0))))
      (setq h (/ h 6.0)))
    (list h s mx)))

(defun mfd--hsv-to-rgb (h s v)
  (if (= s 0) (list v v v)
    (let* ((i (floor (* h 6))) (f (- (* h 6) i))
           (p (* v (- 1 s))) (q (* v (- 1 (* f s)))) (tt (* v (- 1 (* (- 1 f) s))))
           (i6 (mod i 6)))
      (nth i6 (list (list v tt p) (list q v p) (list p v tt)
                    (list p q v) (list tt p v) (list v p q))))))

(defun mfd--srgb-linear (c)
  (if (<= c 0.04045) (/ c 12.92) (expt (/ (+ c 0.055) 1.055) 2.4)))

(defun mfd--luminance (rgb)
  (+ (* 0.2126 (mfd--srgb-linear (car rgb)))
     (* 0.7152 (mfd--srgb-linear (cadr rgb)))
     (* 0.0722 (mfd--srgb-linear (caddr rgb)))))

(defun mfd--contrast-ratio (hex1 hex2)
  (let ((l1 (mfd--luminance (mfd--hex-to-rgb hex1)))
        (l2 (mfd--luminance (mfd--hex-to-rgb hex2))))
    (/ (+ (max l1 l2) 0.05) (+ (min l1 l2) 0.05))))

(defun mfd--lerp-hsv (hex1 hex2 tt)
  (let* ((h1 (apply #'mfd--rgb-to-hsv (mfd--hex-to-rgb hex1)))
         (h2 (apply #'mfd--rgb-to-hsv (mfd--hex-to-rgb hex2)))
         (h (+ (car h1) (* (- (car h2) (car h1)) tt)))
         (s (+ (cadr h1) (* (- (cadr h2) (cadr h1)) tt)))
         (v (+ (caddr h1) (* (- (caddr h2) (caddr h1)) tt))))
    (apply #'mfd--rgb-to-hex (mfd--hsv-to-rgb h s v))))

(defun mfd--find-target-color (src-hex bg-surfaces target direction)
  (if (or (null bg-surfaces)
          (cl-every (lambda (bg) (>= (mfd--contrast-ratio src-hex bg) target)) bg-surfaces))
      src-hex
    (let* ((hsv (apply #'mfd--rgb-to-hsv (mfd--hex-to-rgb src-hex)))
           (h (car hsv)) (s (cadr hsv)) (v (caddr hsv))
           (lo (if (eq direction 'lighter) v 0.0))
           (hi (if (eq direction 'lighter) 1.0 v)))
      (dotimes (_ 30)
        (let* ((mid (/ (+ lo hi) 2.0))
               (mid-hex (apply #'mfd--rgb-to-hex (mfd--hsv-to-rgb h s mid)))
               (ok (cl-every (lambda (bg) (>= (mfd--contrast-ratio mid-hex bg) target)) bg-surfaces)))
          (if (eq direction 'lighter)
              (if ok (setq hi mid) (setq lo mid))
            (if ok (setq lo mid) (setq hi mid)))))
      (apply #'mfd--rgb-to-hex (mfd--hsv-to-rgb h s (/ (+ lo hi) 2.0))))))

(defun mfd--compute-colors (palette level)
  (if (<= level 0) palette
    (let* ((fg (alist-get 'fg palette))
           (bg (alist-get 'bg palette))
           (is-light (< (mfd--luminance (mfd--hex-to-rgb fg))
                        (mfd--luminance (mfd--hex-to-rgb bg))))
           (dir (if is-light 'darker 'lighter))
           (surfaces (delq nil (list bg (alist-get 'float_bg palette) (alist-get 'cursor palette))))
           (tt (/ level 10.0))
           (res (copy-alist palette)))
      (dolist (k '(dim subtle border fg bright))
        (when-let ((src (alist-get k palette)))
          (setf (alist-get k res)
                (mfd--lerp-hsv src (mfd--find-target-color src surfaces 7.1 dir) tt))))
      res)))

(defun mfd--face (plist)
  (let ((p (copy-sequence plist)))
    (when mfd-no-italic (plist-put p :slant 'normal))
    `((t ,p))))

(defun mfd--apply-faces (theme-sym)
  (let* ((raw (or (alist-get theme-sym mfd-palettes)
                  (error "Unknown MFD palette: %s" theme-sym)))
         (c (mfd--compute-colors raw mfd-accessibility-contrast))
         (bg (alist-get 'bg c)) (fg (alist-get 'fg c))
         (dim (alist-get 'dim c)) (bright (alist-get 'bright c))
         (subtle (alist-get 'subtle c)) (visual (alist-get 'visual c))
         (cursor (alist-get 'cursor c)) (border (alist-get 'border c))
         (float-bg (alist-get 'float_bg c))
         (is-light (< (mfd--luminance (mfd--hex-to-rgb fg))
                      (mfd--luminance (mfd--hex-to-rgb bg))))
         (emph (if is-light fg bright))
         (diff-add (mfd--lerp-hsv bg fg 0.12))
         (diff-del (mfd--lerp-hsv bg dim 0.25))
         (diff-chg (mfd--lerp-hsv bg fg 0.06)))
    (custom-theme-set-faces
     theme-sym
     `(default ,(mfd--face `(:foreground ,fg :background ,bg)))
     `(cursor ,(mfd--face `(:background ,bright)))
     `(region ,(mfd--face `(:background ,visual)))
     `(highlight ,(mfd--face `(:background ,cursor)))
     `(fringe ,(mfd--face `(:foreground ,subtle :background ,bg)))
     `(vertical-border ,(mfd--face `(:foreground ,border)))
     `(window-divider ,(mfd--face `(:foreground ,border)))
     `(shadow ,(mfd--face `(:foreground ,dim)))
     `(link ,(mfd--face `(:foreground ,fg :underline t)))
     `(link-visited ,(mfd--face `(:foreground ,dim :underline t)))
     `(minibuffer-prompt ,(mfd--face `(:foreground ,fg :weight bold)))
     `(secondary-selection ,(mfd--face `(:background ,visual)))
     `(trailing-whitespace ,(mfd--face `(:background ,diff-del)))
     `(line-number ,(mfd--face `(:foreground ,subtle :background ,bg)))
     `(line-number-current-line ,(mfd--face `(:foreground ,fg :background ,bg :weight bold)))
     `(mode-line ,(mfd--face `(:foreground ,fg :background ,cursor :weight bold :box nil)))
     `(mode-line-inactive ,(mfd--face `(:foreground ,dim :background ,cursor :box nil)))
     `(header-line ,(mfd--face `(:foreground ,fg :background ,bg :weight bold)))
     `(font-lock-comment-face ,(mfd--face `(:foreground ,dim :slant italic)))
     `(font-lock-comment-delimiter-face ,(mfd--face `(:foreground ,dim :slant italic)))
     `(font-lock-doc-face ,(mfd--face `(:foreground ,dim :slant italic)))
     `(font-lock-string-face ,(mfd--face `(:foreground ,fg :slant italic)))
     `(font-lock-constant-face ,(mfd--face `(:foreground ,fg)))
     `(font-lock-builtin-face ,(mfd--face `(:foreground ,fg :weight bold)))
     `(font-lock-function-name-face ,(mfd--face `(:foreground ,fg :weight bold)))
     `(font-lock-variable-name-face ,(mfd--face `(:foreground ,fg)))
     `(font-lock-keyword-face ,(mfd--face `(:foreground ,emph :weight bold)))
     `(font-lock-type-face ,(mfd--face `(:foreground ,fg :underline t)))
     `(vertico-current ,(mfd--face `(:background ,visual :weight bold)))
     `(corfu-default ,(mfd--face `(:foreground ,fg :background ,float-bg)))
     `(corfu-current ,(mfd--face `(:foreground ,bg :background ,fg :weight bold)))
     `(corfu-border ,(mfd--face `(:foreground ,dim)))
     `(marginalia-documentation ,(mfd--face `(:foreground ,dim :slant italic)))
     `(orderless-match-face-0 ,(mfd--face `(:foreground ,emph :weight bold :underline t)))
     `(consult-highlight ,(mfd--face `(:foreground ,emph :weight bold)))
     `(avy-lead-face ,(mfd--face `(:foreground ,bg :background ,bright :weight bold)))
     `(diff-hl-insert ,(mfd--face `(:background ,diff-add :foreground ,fg)))
     `(diff-hl-delete ,(mfd--face `(:background ,diff-del :foreground ,dim)))
     `(diff-hl-change ,(mfd--face `(:background ,diff-chg :foreground ,fg)))
     `(jinx-misspelled ,(mfd--face `(:underline (:style wave :color ,emph))))
     `(dirvish-hl-line ,(mfd--face `(:background ,visual)))
     `(flycheck-error ,(mfd--face `(:underline (:style wave :color ,emph))))
     `(flycheck-warning ,(mfd--face `(:underline (:style wave :color ,fg))))
     `(flycheck-info ,(mfd--face `(:underline (:style wave :color ,dim))))
     `(posframe-border ,(mfd--face `(:background ,border)))
     `(popup-isearch-match ,(mfd--face `(:background ,bright :foreground ,bg)))
     `(magit-section-heading ,(mfd--face `(:foreground ,fg :weight bold)))
     `(magit-diff-added ,(mfd--face `(:background ,diff-add)))
     `(magit-diff-removed ,(mfd--face `(:background ,diff-del :foreground ,dim)))
     `(magit-diff-context ,(mfd--face `(:foreground ,dim)))
     `(sly-mrepl-output-face ,(mfd--face `(:foreground ,fg)))
     `(geiser-font-lock-repl-output ,(mfd--face `(:foreground ,fg)))
     `(markdown-header-face-1 ,(mfd--face `(:foreground ,emph :weight bold)))
     `(transient-heading ,(mfd--face `(:foreground ,emph :weight bold)))
     `(which-key-key-face ,(mfd--face `(:foreground ,fg :weight bold))))))

(add-hook 'enable-theme-functions
          (lambda (theme)
            (when (and mfd-terminal-cursor-sync
                       (memq theme '(mfd mfd-dark mfd-stealth mfd-mono mfd-flir mfd-paper))
                       (null (display-graphic-p)))
              (when-let* ((raw (alist-get theme mfd-palettes))
                          (c (mfd--compute-colors raw mfd-accessibility-contrast)))
                (send-string-to-terminal (format "\e]12;%s\a" (alist-get 'bright c)))))))

(provide 'mfd)
  ;;; mfd.el ends here
