S = {}

S.BorderSimple = { "─", "│", "─", "│", "┌", "┐", "┘", "└" }

S.Border = {
  { "┌", "Normal" },
  { "─", "Normal" },
  { "┐", "Normal" },
  { "│", "Normal" },
  { "┘", "Normal" },
  { "─", "Normal" },
  { "└", "Normal" },
  { "│", "Normal" },
}

S.VimModeLowercaseFull = {
  ["n"] = "normal",
  ["no"] = "normal",
  ["nov"] = "normal",
  ["noV"] = "normal",
  ["no\22"] = "normal",
  ["niI"] = "normal",
  ["niR"] = "normal",
  ["niV"] = "normal",
  ["nt"] = "normal",
  ["ntT"] = "normal",
  ["v"] = "visual",
  ["vs"] = "visual",
  ["V"] = "visual",
  ["Vs"] = "visual",
  ["\22"] = "visual",
  ["\22s"] = "visual",
  ["s"] = "select",
  ["S"] = "select",
  ["\19"] = "insert",
  ["i"] = "insert",
  ["ic"] = "insert",
  ["ix"] = "insert",
  ["R"] = "replace",
  ["Rc"] = "replace",
  ["Rx"] = "replace",
  ["Rv"] = "replace",
  ["Rvc"] = "replace",
  ["Rvx"] = "replace",
  ["c"] = "command",
  ["cv"] = "command",
  ["ce"] = "command",
  ["r"] = "...",
  ["rm"] = "M",
  ["r?"] = "?",
  ["!"] = "󰩌",
  ["t"] = "terminal",
}

S.VimModeTwo = {
  ["n"] = "NO",
  ["no"] = "OP",
  ["nov"] = "OC",
  ["noV"] = "OL",
  ["no\x16"] = "OB",
  ["\x16"] = "VB",
  ["niI"] = "IN",
  ["niR"] = "RE",
  ["niV"] = "RV",
  ["nt"] = "NT",
  ["ntT"] = "TM",
  ["v"] = "VI",
  ["vs"] = "VI",
  ["V"] = "VL",
  ["Vs"] = "VL",
  ["\x16s"] = "VB",
  ["s"] = "SE",
  ["S"] = "SL",
  ["\x13"] = "SB",
  ["i"] = "IN",
  ["ic"] = "IC",
  ["ix"] = "IX",
  ["R"] = "RE",
  ["Rc"] = "RC",
  ["Rx"] = "RX",
  ["Rv"] = "RV",
  ["Rvc"] = "RC",
  ["Rvx"] = "RX",
  ["c"] = "CO",
  ["cv"] = "CV",
  ["r"] = "PR",
  ["rm"] = "PM",
  ["r?"] = "P?",
  ["!"] = "SH",
  ["t"] = "TE",
}

---@return string # Icon
S.Icons = {
  mode = "",
  normal = "",
  visual = "",
  insert = "",
  command = "",
  git = {
    branch = "",
    added = " ",
    modified = "󰝤 ",
    modified_simple = "~ ",
    removed = " ",
  },
  diagnostics = {
    error = " ",
    warn = " ",
    info = " ",
    hint = "󰌵 ",
    hintfull = " ",
  },
  ui = {
    box_empty = "󰄱",
    box_check = "",
    circle_rightwards_arrow = "",
    circle_x = "󰰱",
    circle_filled = "●",
    circle_outline = "○",
    lock = "",
    recording = "",
    angle_down = "",
    angle_left = "",
    angle_right = "",
    angle_up = "",
    arrow_down = "↓",
    arrow_left = "←",
    arrow_right = "→",
    arrow_up = "↑",
    cross = "󰅖",
    checkmark = "󰄬",
    diamond = "◆",
    dot_large = "•",
    dot = "",
    ellipsis = "…",
  },
  kinds = {
    Array = "",
    Boolean = "󰨙",
    Class = "",
    Codeium = "󰘦",
    Color = "",
    Control = "",
    Collapsed = "",
    Constant = "󰏿",
    Constructor = "",
    Copilot = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "",
    Function = "󰊕",
    Interface = "",
    Key = "",
    Keyword = "",
    Method = "󰊕",
    Module = "",
    Namespace = "󰦮",
    Null = "",
    Number = "󰎠",
    Object = "",
    Operator = "",
    Package = "",
    Property = "",
    Reference = "",
    Snippet = "",
    String = "",
    Struct = "󰆼",
    TabNine = "󰏚",
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "󰀫",
  },
}

return S
