[colors-dark]
foreground = D0D0D8
background = 08080C
cursor = 08080C F0F0FF
selection-background = 1A1A22
selection-foreground = D0D0D8

regular0 = 08080C
regular1 = 727276
# regular2 = 85858A
regular2 = FFF779
# regular3 = #97979D ## String
regular3 = FFF779
regular4 = AAAAB1 ## Dir
regular5 = BDBDC4
regular6 = D0D0D8 ## Flag
regular7 = D0D0D8

bright0 = 6A6A7A
bright1 = D0D0D8
# bright2 = D8D8E0
bright2 = FFF779
bright3 = DFDFE8 ## File
bright4 = E7E7EF ## Dir
bright5 = EEEEF7
bright6 = F6F6FF
bright7 = F6F6FF
