[colors-dark]
foreground = 9EB180
background = 1E2D1E
cursor = 1E2D1E AABC88
selection-background = 2A3D2A
selection-foreground = 9EB180

regular0 = 1E2D1E
regular1 = 7C8B65
# regular2 = 83936A
regular2 = FFF779
# regular3 = 8A9A70 ## String
regular3 = FFF779
regular4 = 90A275 ## Dir
regular5 = 97A97B
regular6 = 9EB180 ## Flag
regular7 = 9EB180

bright0 = 638563
bright1 = 9EB180
# bright2 = A0B382
bright2 = FFF779
bright3 = A2B583 ## File
bright4 = A4B885 ## Dir
bright5 = A6BA86
bright6 = A8BC88
bright7 = AEC38D
