[colors-dark]
foreground = 84A684
background = 0D1410
cursor = 0D1410 9ABB9A
selection-background = 1A2A1A
selection-foreground = 84A684

regular0 = 0D1410
regular1 = 5F775F
# regular1 = 668066
regular2 = FFF779
# regular2 = 6E8A6E ## String
regular3 = FFF779
regular4 = 759375 ## Dir
regular5 = 7D9D7D
regular6 = 84A684 ## Flag
regular7 = 84A684

bright0 = 567756
bright1 = 84A684
# bright2 = 87AA87
bright2 = FFF779
bright3 = 8BAE8B
bright4 = 8EB38E
bright5 = 91B791
bright6 = 95BB95
# bright7 = 9FC89F
bright7 = FFBE89
