local a = require("wezterm").action
--stylua: ignore start
local default_keys = {
  keys = {
    { key = "]",        mods = "SHIFT|SUPER", action = a.ActivateTabRelative(1)  },
    { key = "]",        mods = "LEADER",      action = a.ActivateTabRelative(1)  },
    { key = "Tab",      mods = "CTRL",        action = a.ActivateTabRelative(1)  },
    { key = "PageDown", mods = "CTRL",        action = a.ActivateTabRelative(1)  },
    { key = "}",        mods = "SUPER",       action = a.ActivateTabRelative(1)  },
    { key = "}",        mods = "SHIFT|SUPER", action = a.ActivateTabRelative(1)  },
    { key = "Tab",      mods = "SHIFT|CTRL",  action = a.ActivateTabRelative(-1) },
    { key = "PageUp",   mods = "CTRL",        action = a.ActivateTabRelative(-1) },
    { key = "{",        mods = "SUPER",       action = a.ActivateTabRelative(-1) },
    { key = "{",        mods = "SHIFT|SUPER", action = a.ActivateTabRelative(-1) },
    { key = "[",        mods = "SHIFT|SUPER", action = a.ActivateTabRelative(-1) },
    { key = "[",        mods = "LEADER",      action = a.ActivateTabRelative(-1) },
    { key = "(", mods = "CTRL",       action = a.ActivateTab(-1) },
    { key = "(", mods = "SHIFT|CTRL", action = a.ActivateTab(-1) },
    { key = "9", mods = "SHIFT|CTRL", action = a.ActivateTab(-1) },
    { key = "9", mods = "SUPER",      action = a.ActivateTab(-1) },
    { key = "!", mods = "CTRL",       action = a.ActivateTab(0) },
    { key = "!", mods = "SHIFT|CTRL", action = a.ActivateTab(0) },
    { key = "1", mods = "SHIFT|CTRL", action = a.ActivateTab(0) },
    { key = "1", mods = "SUPER",      action = a.ActivateTab(0) },
    { key = "2", mods = "SHIFT|CTRL", action = a.ActivateTab(1) },
    { key = "2", mods = "SUPER",      action = a.ActivateTab(1) },
    { key = "@", mods = "CTRL",       action = a.ActivateTab(1) },
    { key = "@", mods = "SHIFT|CTRL", action = a.ActivateTab(1) },
    { key = "#", mods = "CTRL",       action = a.ActivateTab(2) },
    { key = "#", mods = "SHIFT|CTRL", action = a.ActivateTab(2) },
    { key = "3", mods = "SHIFT|CTRL", action = a.ActivateTab(2) },
    { key = "3", mods = "SUPER",      action = a.ActivateTab(2) },
    { key = "4", mods = "SHIFT|CTRL", action = a.ActivateTab(3) },
    { key = "4", mods = "SUPER",      action = a.ActivateTab(3) },
    { key = "$", mods = "CTRL",       action = a.ActivateTab(3) },
    { key = "$", mods = "SHIFT|CTRL", action = a.ActivateTab(3) },
    { key = "%", mods = "CTRL",       action = a.ActivateTab(4) },
    { key = "%", mods = "SHIFT|CTRL", action = a.ActivateTab(4) },
    { key = "5", mods = "SHIFT|CTRL", action = a.ActivateTab(4) },
    { key = "5", mods = "SUPER",      action = a.ActivateTab(4) },
    { key = "6", mods = "SHIFT|CTRL", action = a.ActivateTab(5) },
    { key = "6", mods = "SUPER",      action = a.ActivateTab(5) },
    { key = "^", mods = "CTRL",       action = a.ActivateTab(5) },
    { key = "^", mods = "SHIFT|CTRL", action = a.ActivateTab(5) },
    { key = "&", mods = "CTRL",       action = a.ActivateTab(6) },
    { key = "&", mods = "SHIFT|CTRL", action = a.ActivateTab(6) },
    { key = "7", mods = "SHIFT|CTRL", action = a.ActivateTab(6) },
    { key = "7", mods = "SUPER",      action = a.ActivateTab(6) },
    { key = "8", mods = "SHIFT|CTRL", action = a.ActivateTab(7) },
    { key = "8", mods = "SUPER",      action = a.ActivateTab(7) },
    { key = "*", mods = "CTRL",       action = a.ActivateTab(7) },
    { key = "*", mods = "SHIFT|CTRL", action = a.ActivateTab(7) },
    { key = "v", mods = "LEADER",     action = a.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
    { key = "s",     mods = "LEADER",         action = a.SplitVertical  ({ domain = "CurrentPaneDomain" }) },
    { key = "\"",    mods = "SHIFT|ALT|CTRL", action = a.SplitVertical  ({ domain = "CurrentPaneDomain" }) },
    { key = "\"",    mods = "ALT|CTRL",       action = a.SplitVertical  ({ domain = "CurrentPaneDomain" }) },
    { key = "\"",    mods = "SHIFT|ALT|CTRL", action = a.SplitVertical  ({ domain = "CurrentPaneDomain" }) },
    { key = "%",     mods = "ALT|CTRL",       action = a.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
    { key = "5",     mods = "SHIFT|ALT|CTRL", action = a.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
    { key = "%",     mods = "SHIFT|ALT|CTRL", action = a.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
    { key = "C",     mods = "CTRL",           action = a.CopyTo   ("Clipboard")        },
    { key = "Copy",  mods = "NONE",           action = a.CopyTo   ("Clipboard")        },
    { key = "C",     mods = "SHIFT|CTRL",     action = a.CopyTo   ("Clipboard")        },
    { key = "c",     mods = "SHIFT|CTRL",     action = a.CopyTo   ("Clipboard")        },
    { key = "c",     mods = "SUPER",          action = a.CopyTo   ("Clipboard")        },
    { key = "Insert",mods = "CTRL",           action = a.CopyTo   ("PrimarySelection") },
    { key = "Paste", mods = "NONE",           action = a.PasteFrom("Clipboard")        },
    { key = "v",     mods = "SHIFT|CTRL",     action = a.PasteFrom("Clipboard")        },
    { key = "v",     mods = "SUPER",          action = a.PasteFrom("Clipboard")        },
    { key = "V",     mods = "CTRL",           action = a.PasteFrom("Clipboard")        },
    { key = "V",     mods = "SHIFT|CTRL",     action = a.PasteFrom("Clipboard")        },
    { key = "Insert",mods = "SHIFT",          action = a.PasteFrom("PrimarySelection") },
    { key = "y",     mods = "NONE",           action = a.Multiple({ { CopyTo =  "ClipboardAndPrimarySelection" }, { Multiple = { "ScrollToBottom", { CopyMode =  "Close" } } } }) },
    { key = "F",     mods = "CTRL",           action = a.Search("CurrentSelectionOrEmptyString") },
    { key = "F",     mods = "SHIFT|CTRL",     action = a.Search("CurrentSelectionOrEmptyString") },
    { key = "f",     mods = "SHIFT|CTRL",     action = a.Search("CurrentSelectionOrEmptyString") },
    { key = "f",     mods = "SUPER",          action = a.Search("CurrentSelectionOrEmptyString") },
    { key = "T",     mods = "CTRL",           action = a.SpawnTab("CurrentPaneDomain") },
    { key = "T",     mods = "SHIFT|CTRL",     action = a.SpawnTab("CurrentPaneDomain") },
    { key = "t",     mods = "SHIFT|CTRL",     action = a.SpawnTab("CurrentPaneDomain") },
    { key = "t",     mods = "SUPER",          action = a.SpawnTab("CurrentPaneDomain") },
    { key = "t",     mods = "LEADER",         action = a.SpawnTab("CurrentPaneDomain") },
    { key = "W",     mods = "CTRL",           action = a.CloseCurrentTab({ confirm = true }) },
    { key = "W",     mods = "SHIFT|CTRL",     action = a.CloseCurrentTab({ confirm = true }) },
    { key = "w",     mods = "SHIFT|CTRL",     action = a.CloseCurrentTab({ confirm = true }) },
    { key = "w",     mods = "SUPER",          action = a.CloseCurrentTab({ confirm = true }) },
    { key = "k",     mods = "SHIFT|CTRL",     action = a.ClearScrollback("ScrollbackOnly") },
    { key = "k",     mods = "SUPER",          action = a.ClearScrollback("ScrollbackOnly") },
    { key = "K",     mods = "CTRL",           action = a.ClearScrollback("ScrollbackOnly") },
    { key = "K",     mods = "SHIFT|CTRL",     action = a.ClearScrollback("ScrollbackOnly") },
    { key = "h",          mods = "LEADER",     action = a.ActivatePaneDirection("Left")  },
    { key = "j",          mods = "LEADER",     action = a.ActivatePaneDirection("Down")  },
    { key = "k",          mods = "LEADER",     action = a.ActivatePaneDirection("Up")    },
    { key = "l",          mods = "LEADER",     action = a.ActivatePaneDirection("Right") },
    { key = "LeftArrow",  mods = "SHIFT|CTRL", action = a.ActivatePaneDirection("Left")  },
    { key = "RightArrow", mods = "SHIFT|CTRL", action = a.ActivatePaneDirection("Right") },
    { key = "UpArrow",    mods = "SHIFT|CTRL", action = a.ActivatePaneDirection("Up")    },
    { key = "DownArrow",  mods = "SHIFT|CTRL", action = a.ActivatePaneDirection("Down")  },
    { key = "M",     mods = "CTRL",           action = a.Hide                    },
    { key = "M",     mods = "SHIFT|CTRL",     action = a.Hide                    },
    { key = "m",     mods = "SHIFT|CTRL",     action = a.Hide                    },
    { key = "m",     mods = "SUPER",          action = a.Hide                    },
    { key = "l",     mods = "SHIFT|CTRL",     action = a.ShowDebugOverlay        },
    { key = "L",     mods = "CTRL",           action = a.ShowDebugOverlay        },
    { key = "L",     mods = "SHIFT|CTRL",     action = a.ShowDebugOverlay        },
    { key = "Enter", mods = "ALT",            action = a.ToggleFullScreen        },
    { key = "-",     mods = "CTRL",           action = a.DecreaseFontSize        },
    { key = "-",     mods = "SHIFT|CTRL",     action = a.DecreaseFontSize        },
    { key = "-",     mods = "SUPER",          action = a.DecreaseFontSize        },
    { key = "_",     mods = "CTRL",           action = a.DecreaseFontSize        },
    { key = "_",     mods = "SHIFT|CTRL",     action = a.DecreaseFontSize        },
    { key = "+",     mods = "CTRL",           action = a.IncreaseFontSize        },
    { key = "+",     mods = "SHIFT|CTRL",     action = a.IncreaseFontSize        },
    { key = "=",     mods = "CTRL",           action = a.IncreaseFontSize        },
    { key = "=",     mods = "SHIFT|CTRL",     action = a.IncreaseFontSize        },
    { key = "=",     mods = "SUPER",          action = a.IncreaseFontSize        },
    { key = "0",     mods = "CTRL",           action = a.ResetFontSize           },
    { key = "0",     mods = "SHIFT|CTRL",     action = a.ResetFontSize           },
    { key = "0",     mods = "SUPER",          action = a.ResetFontSize           },
    { key = ")",     mods = "CTRL",           action = a.ResetFontSize           },
    { key = ")",     mods = "SHIFT|CTRL",     action = a.ResetFontSize           },
    { key = "N",     mods = "CTRL",           action = a.SpawnWindow             },
    { key = "N",     mods = "SHIFT|CTRL",     action = a.SpawnWindow             },
    { key = "n",     mods = "SHIFT|CTRL",     action = a.SpawnWindow             },
    { key = "n",     mods = "SUPER",          action = a.SpawnWindow             },
    { key = "X",     mods = "CTRL",           action = a.ActivateCopyMode        },
    { key = "X",     mods = "SHIFT|CTRL",     action = a.ActivateCopyMode        },
    { key = "c",     mods = "LEADER",         action = a.ActivateCopyMode        },
    { key = "x",     mods = "SHIFT|CTRL",     action = a.ActivateCopyMode        },
    { key = "Z",     mods = "CTRL",           action = a.TogglePaneZoomState     },
    { key = "Z",     mods = "SHIFT|CTRL",     action = a.TogglePaneZoomState     },
    { key = "z",     mods = "SHIFT|CTRL",     action = a.TogglePaneZoomState     },
    { key = "z",     mods = "LEADER",         action = a.TogglePaneZoomState     },
    { key = "r",     mods = "SHIFT|CTRL",     action = a.ReloadConfiguration     },
    { key = "r",     mods = "SUPER",          action = a.ReloadConfiguration     },
    { key = "R",     mods = "CTRL",           action = a.ReloadConfiguration     },
    { key = "R",     mods = "SHIFT|CTRL",     action = a.ReloadConfiguration     },
    { key = "P",          mods = "CTRL",       action = a.ActivateCommandPalette },
    { key = "P",          mods = "SHIFT|CTRL", action = a.ActivateCommandPalette },
    { key = "p",          mods = "SHIFT|CTRL", action = a.ActivateCommandPalette },
    { key = "phys:Space", mods = "LEADER",     action = a.ActivateCommandPalette },
    { key = "m", mods = "LEADER", action = a.ActivateKeyTable({ name = "move_tab", one_shot = false, prevent_fallback = false, replace_current = false, until_unknown = false }) },
    { key = "r", mods = "LEADER", action = a.ActivateKeyTable({ name = "resize_pane", one_shot = false, prevent_fallback = false, replace_current = false, until_unknown = false }) },
    { key = "o", mods = "LEADER",       action = a.RotatePanes("Clockwise") },
    { key = "u", mods = "SHIFT|CTRL",   action = a.CharSelect({ copy_on_select = true, copy_to = "ClipboardAndPrimarySelection" }) },
    { key = "U", mods = "CTRL",         action = a.CharSelect({ copy_on_select = true, copy_to = "ClipboardAndPrimarySelection" }) },
    { key = "U", mods = "SHIFT|CTRL",   action = a.CharSelect({ copy_on_select = true, copy_to = "ClipboardAndPrimarySelection" }) },
    { key = "w", mods = "LEADER",       action = a.ShowLauncherArgs({ flags = "FUZZY|WORKSPACES" }) },
    { key = "x", mods = "LEADER",       action = a.CloseCurrentPane({ confirm = true }) },
    { key = "{",          mods = "SHIFT|LEADER",   action = a.MoveTabRelative(-1) },
    { key = "}",          mods = "SHIFT|LEADER",   action = a.MoveTabRelative(1)  },
    { key = "PageUp",     mods = "SHIFT|CTRL",     action = a.MoveTabRelative(-1) },
    { key = "PageDown",   mods = "SHIFT|CTRL",     action = a.MoveTabRelative(1)  },
    { key = "phys:Space", mods = "SHIFT|CTRL",     action = a.QuickSelect         },
    { key = "PageUp",     mods = "SHIFT",          action = a.ScrollByPage(-1)    },
    { key = "PageDown",   mods = "SHIFT",          action = a.ScrollByPage(1)     },
    { key = "LeftArrow",  mods = "SHIFT|ALT|CTRL", action = a.AdjustPaneSize({ "Left",  1 }) },
    { key = "RightArrow", mods = "SHIFT|ALT|CTRL", action = a.AdjustPaneSize({ "Right", 1 }) },
    { key = "UpArrow",    mods = "SHIFT|ALT|CTRL", action = a.AdjustPaneSize({ "Up",    1 }) },
    { key = "DownArrow",  mods = "SHIFT|ALT|CTRL", action = a.AdjustPaneSize({ "Down",  1 }) },
  },

  key_tables = {
    copy_mode = {
      { key = "Tab",        mods = "NONE",  action = a.CopyMode("MoveForwardWord")  },
      { key = "RightArrow", mods = "ALT",   action = a.CopyMode("MoveForwardWord")  },
      { key = "w",          mods = "NONE",  action = a.CopyMode("MoveForwardWord")  },
      { key = "f",          mods = "ALT",   action = a.CopyMode("MoveForwardWord")  },
      { key = "Tab",        mods = "SHIFT", action = a.CopyMode("MoveBackwardWord") },
      { key = "b",          mods = "NONE",  action = a.CopyMode("MoveBackwardWord") },
      { key = "b",          mods = "ALT",   action = a.CopyMode("MoveBackwardWord") },
      { key = "LeftArrow",  mods = "ALT",   action = a.CopyMode("MoveBackwardWord") },
      { key = "Enter",      mods = "NONE",  action = a.CopyMode("MoveToStartOfNextLine")         },
      { key = "Escape",     mods = "NONE",  action = a.Multiple({ "ScrollToBottom", { CopyMode = "Close" } }) },
      { key = "g",          mods = "CTRL",  action = a.Multiple({ "ScrollToBottom", { CopyMode = "Close" } }) },
      { key = "c",          mods = "CTRL",  action = a.Multiple({ "ScrollToBottom", { CopyMode = "Close" } }) },
      { key = "q",          mods = "NONE",  action = a.Multiple({ "ScrollToBottom", { CopyMode = "Close" } }) },
      { key = "Space",      mods = "NONE",  action = a.CopyMode({ SetSelectionMode = "Cell" }) },
      { key = "V",          mods = "NONE",  action = a.CopyMode({ SetSelectionMode = "Line" }) },
      { key = "V",          mods = "SHIFT", action = a.CopyMode({ SetSelectionMode = "Line" }) },
      { key = "v",          mods = "NONE",  action = a.CopyMode({ SetSelectionMode = "Cell" }) },
      { key = "v",          mods = "CTRL",  action = a.CopyMode({ SetSelectionMode = "Block"}) },
      { key = "$",          mods = "NONE",  action = a.CopyMode("MoveToEndOfLineContent") },
      { key = "$",          mods = "SHIFT", action = a.CopyMode("MoveToEndOfLineContent") },
      { key = "End",        mods = "NONE",  action = a.CopyMode("MoveToEndOfLineContent") },
      { key = ",",          mods = "NONE",  action = a.CopyMode("JumpReverse")            },
      { key = ";",          mods = "NONE",  action = a.CopyMode("JumpAgain")              },
      { key = "0",          mods = "NONE",  action = a.CopyMode("MoveToStartOfLine")      },
      { key = "Home",       mods = "NONE",  action = a.CopyMode("MoveToStartOfLine")      },
      { key = "F",          mods = "NONE",  action = a.CopyMode({ JumpBackward = { prev_char = false } }) },
      { key = "F",          mods = "SHIFT", action = a.CopyMode({ JumpBackward = { prev_char = false } }) },
      { key = "T",          mods = "NONE",  action = a.CopyMode({ JumpBackward = { prev_char = true } }) },
      { key = "T",          mods = "SHIFT", action = a.CopyMode({ JumpBackward = { prev_char = true } }) },
      { key = "f",          mods = "NONE",  action = a.CopyMode({ JumpForward = { prev_char = false } }) },
      { key = "t",          mods = "NONE",  action = a.CopyMode({ JumpForward = { prev_char = true } }) },
      { key = "G",          mods = "NONE",  action = a.CopyMode("MoveToScrollbackBottom") },
      { key = "G",          mods = "SHIFT", action = a.CopyMode("MoveToScrollbackBottom") },
      { key = "H",          mods = "NONE",  action = a.CopyMode("MoveToViewportTop")      },
      { key = "H",          mods = "SHIFT", action = a.CopyMode("MoveToViewportTop")      },
      { key = "L",          mods = "NONE",  action = a.CopyMode("MoveToViewportBottom")   },
      { key = "L",          mods = "SHIFT", action = a.CopyMode("MoveToViewportBottom")   },
      { key = "M",          mods = "NONE",  action = a.CopyMode("MoveToViewportMiddle")   },
      { key = "M",          mods = "SHIFT", action = a.CopyMode("MoveToViewportMiddle")   },
      { key = "O",          mods = "NONE",  action = a.CopyMode("MoveToSelectionOtherEndHoriz") },
      { key = "O",          mods = "SHIFT", action = a.CopyMode("MoveToSelectionOtherEndHoriz") },
      { key = "^",          mods = "NONE",  action = a.CopyMode("MoveToStartOfLineContent") },
      { key = "^",          mods = "SHIFT", action = a.CopyMode("MoveToStartOfLineContent") },
      { key = "m",          mods = "ALT",   action = a.CopyMode("MoveToStartOfLineContent") },
      { key = "o",          mods = "NONE",  action = a.CopyMode("MoveToSelectionOtherEnd")  },
      { key = "d",          mods = "CTRL",  action = a.CopyMode({ MoveByPage = (0.5) }) },
      { key = "u",          mods = "CTRL",  action = a.CopyMode({ MoveByPage = (-0.5) }) },
      { key = "e",          mods = "NONE",  action = a.CopyMode("MoveForwardWordEnd")       },
      { key = "g",          mods = "NONE",  action = a.CopyMode("MoveToScrollbackTop")      },
      { key = "h",          mods = "NONE",  action = a.CopyMode("MoveLeft")                 },
      { key = "LeftArrow",  mods = "NONE",  action = a.CopyMode("MoveLeft")                 },
      { key = "j",          mods = "NONE",  action = a.CopyMode("MoveDown")                 },
      { key = "DownArrow",  mods = "NONE",  action = a.CopyMode("MoveDown")                 },
      { key = "k",          mods = "NONE",  action = a.CopyMode("MoveUp")                   },
      { key = "UpArrow",    mods = "NONE",  action = a.CopyMode("MoveUp")                   },
      { key = "l",          mods = "NONE",  action = a.CopyMode("MoveRight")                },
      { key = "RightArrow", mods = "NONE",  action = a.CopyMode("MoveRight")                },
      { key = "PageUp",     mods = "NONE",  action = a.CopyMode("PageUp")                   },
      { key = "b",          mods = "CTRL",  action = a.CopyMode("PageUp")                   },
      { key = "f",          mods = "CTRL",  action = a.CopyMode("PageDown")                 },
      { key = "PageDown",   mods = "NONE",  action = a.CopyMode("PageDown")                 },
    },

    move_tab = {
      { key = "Enter", mods = "NONE", action = a.PopKeyTable },
      { key = "Escape", mods = "NONE", action = a.PopKeyTable },
      { key = "c", mods = "CTRL", action = a.PopKeyTable },
      { key = "h", mods = "NONE", action = a.MoveTabRelative(-1) },
      { key = "j", mods = "NONE", action = a.MoveTabRelative(-1) },
      { key = "k", mods = "NONE", action = a.MoveTabRelative(1) },
      { key = "l", mods = "NONE", action = a.MoveTabRelative(1) },
    },

    resize_pane = {
      { key = "Enter", mods = "NONE", action = a.PopKeyTable },
      { key = "Escape", mods = "NONE", action = a.PopKeyTable },
      { key = "c", mods = "CTRL", action = a.PopKeyTable },
      { key = "h", mods = "NONE", action = a.AdjustPaneSize{ "Left", 1 } },
      { key = "j", mods = "NONE", action = a.AdjustPaneSize{ "Down", 1 } },
      { key = "k", mods = "NONE", action = a.AdjustPaneSize{ "Up", 1 } },
      { key = "l", mods = "NONE", action = a.AdjustPaneSize{ "Right", 1 } },
    },

    search_mode = {
      { key = "Enter", mods = "NONE", action = a.CopyMode "PriorMatch" },
      { key = "Escape", mods = "NONE", action = a.CopyMode "Close" },
      { key = "n", mods = "CTRL", action = a.CopyMode "NextMatch" },
      { key = "p", mods = "CTRL", action = a.CopyMode "PriorMatch" },
      { key = "r", mods = "CTRL", action = a.CopyMode "CycleMatchType" },
      { key = "u", mods = "CTRL", action = a.CopyMode "ClearPattern" },
      { key = "PageUp", mods = "NONE", action = a.CopyMode "PriorMatchPage" },
      { key = "PageDown", mods = "NONE", action = a.CopyMode "NextMatchPage" },
      { key = "UpArrow", mods = "NONE", action = a.CopyMode "PriorMatch" },
      { key = "DownArrow", mods = "NONE", action = a.CopyMode "NextMatch" },
    },

  }
}
--stylua: ignore start
