# ~  Bash
# Sourced from /etc/profile.d/bashdotdir.sh

# Environment variables
. "$BASHDOTDIR/settings/env.bash"
# PATH
. "$BASHDOTDIR/settings/path.bash"
# Aliases
. "$BASHDOTDIR/settings/alias.bash"
# Bash shell options
. "$BASHDOTDIR/settings/options.bash"

# Prompt
eval "$(starship init bash)"
