# ~  Bash

# ~ ! Sourced from /etc/bash.bashrc

settings="$BASHDOTDIR/settings"

# ~  Environment variables
source $settings/env.sh

# ~  PATH
source $settings/path.sh

# ~  Aliases
source $settings/alias.sh

eval "$(starship init bash)"
