# Rose pine

[manager]
cwd = { fg = "#9ccfd8" }
hovered = { fg = "#e0def4", bg = "#26233a" }
preview_hovered = { underline = true }
find_keyword = { fg = "#f6c177", italic = true }
find_position = { fg = "#eb6f92", bg = "reset", italic = true }
marker_selected = { fg = "#9ccfd8", bg = "#9ccfd8" }
marker_copied = { fg = "#f6c177", bg = "#f6c177" }
marker_cut = { fg = "#B4637A", bg = "#B4637A" }
tab_active = { fg = "#e0def4", bg = "#191724" }
tab_inactive = { fg = "#e0def4", bg = "#2A273F" }
tab_width = 1
border_symbol = "│"
border_style = { fg = "#524f67" }
syntect_theme = "~/.config/yazi/catppuccin-mocha.tmTheme"

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#2A273F", bg = "#2A273F" }
mode_normal = { fg = "#191724", bg = "#ebbcba", bold = true }
mode_select = { fg = "#e0def4", bg = "#9ccfd8", bold = true }
mode_unset = { fg = "#e0def4", bg = "#b4637a", bold = true }
progress_label = { fg = "#e0def4", bold = true }
progress_normal = { fg = "#191724", bg = "#2A273F" }
progress_error = { fg = "#B4637A", bg = "#2A273F" }
permissions_t = { fg = "#31748f" }
permissions_r = { fg = "#f6c177" }
permissions_w = { fg = "#B4637A" }
permissions_x = { fg = "#9ccfd8" }
permissions_s = { fg = "#524f67" }

[input]
border = { fg = "#524f67" }
title = {}
value = {}
selected = { reversed = true }

[select]
border = { fg = "#524f67" }
active = { fg = "#eb6f92" }
inactive = {}

[tasks]
border = { fg = "#524f67" }
title = {}
hovered = { underline = true }

[which]
mask = { bg = "#313244" }
cand = { fg = "#9ccfd8" }
rest = { fg = "#9399b2" }
desc = { fg = "#eb6f92" }
separator = "  "
separator_style = { fg = "#585b70" }

[help]
on = { fg = "#eb6f92" }
exec = { fg = "#9ccfd8" }
desc = { fg = "#9399b2" }
hovered = { bg = "#585b70", bold = true }
footer = { fg = "#2A273F", bg = "#e0def4" }

[filetype]
rules = [
    { mime = "image/*", fg = "#9ccfd8" },
    { mime = "video/*", fg = "#f6c177" },
    { mime = "audio/*", fg = "#f6c177" },
    { mime = "application/zip", fg = "#eb6f92" },
    { mime = "application/gzip", fg = "#eb6f92" },
    { mime = "application/x-tar", fg = "#eb6f92" },
    { mime = "application/x-bzip", fg = "#eb6f92" },
    { mime = "application/x-bzip2", fg = "#eb6f92" },
    { mime = "application/x-7z-compressed", fg = "#eb6f92" },
    { mime = "application/x-rar", fg = "#eb6f92" },
    { name = "*", fg = "#e0def4" },
    { name = "*/", fg = "#524f67" },
]
