#!/bin/sh

# ~  Autostart

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr -s 1920x1080
pkill picom
picom -fb --experimental-backends &
$HOME/.config/polybar/launch.sh
# nitrogen --restore

# ~  Workspaces

bspc monitor -d 1 2 3 4 5

# ~  Window

bspc config border_width            1
bspc config window_gap              4
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer   true
bspc config borderless_monocle      true
bspc config gapless_monocle         true
