return {
  "ibhagwan/fzf-lua",
  cmd = "FzfLua",
  opts = {
    { "max-perf", "telescope" },
    fzf_opts = { ["--layout"] = "reverse", ["--marker"] = false },
    winopts = {
      header = false,
      height = 0.4,
      width = 0.8,
      row = 0.5,
      col = 0.5,
      border = GRIM.static.border,
      -- treesitter = true,
      backdrop = 100,
      preview = {
        border = "noborder",
        wrap = "nowrap",
        hidden = "hidden",
        vertical = "down:50%",
        horizontal = "right:50%",
        layout = "horizontal",
        scrollbar = false,
        scrolloff = "-2",
        scrollchars = { "", "" },
      },
    },
    keymap = {
      builtin = {
        ["<M-Esc>"] = "hide",
        ["<F1>"] = "toggle-help",
        ["<F2>"] = "toggle-preview-wrap",
        ["<M-p>"] = "toggle-preview",
      },
      fzf = {
        true,
        ["ctrl-z"] = "abort",
        ["ctrl-u"] = "unix-line-discard",
        ["ctrl-f"] = "half-page-down",
        ["ctrl-b"] = "half-page-up",
        ["ctrl-a"] = "beginning-of-line",
        ["ctrl-e"] = "end-of-line",
        ["alt-a"] = "toggle-all",
        ["alt-g"] = "first",
        ["alt-G"] = "last",
        ["alt-p"] = "toggle-preview",
      },
    },
    actions = { true },
    lsp_code_actions = { winopts = { width = 0.4 } },
    files = { winopts = { width = 0.4 } },
    oldfiles = { winopts = { title = " Old files ", width = 0.4 } },
    buffers = { winopts = { width = 0.4 } },
    helptags = {
      winopts = { width = 1.0, height = 0.5, row = 1.0, col = 0.0 },
    },
  },
}
