return {
  -- "folke/noice.nvim",
  -- event = "VeryLazy",
  -- opts = {
  --   presets = {
  --     bottom_search = true,
  --     command_palette = true,
  --     long_message_to_split = true,
  --   },
  --   cmdline = { enabled = true, view = "cmdline" },
  --   messages = {
  --     enabled = true,
  --     view = "mini",
  --     view_warn = "notify",
  --     view_error = "notify",
  --     view_history = "messages",
  --     view_search = "",
  --   },
  --   notify = { enabled = true, view = "notify" },
  --   popupmenu = { enabled = true, backend = "nui" },
  --   lsp = {
  --     message = { enabled = false, view = "notify" },
  --     hover = { enabled = false, silent = true },
  --     progress = { enabled = false },
  --     signature = { enabled = false },
  --     override = {
  --       ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
  --       ["vim.lsp.util.stylize_markdown"] = true,
  --       ["cmp.entry.get_documentation"] = true,
  --     },
  --   },
  --   -- stylua: ignore start
  --   views = {
  --     mini = { win_options = { winblend = 100 } },
  --     popup = { border = { style = S.Border }, close = { keys = { "q", "<C-c>" } } },
  --     notify = { backend = "notify", replace = true, merge = true },
  --     messages = { view = "popup" },
  --     split = { enter = true, win_options = { wrap = false }, close = { keys = { "q", "<C-c>" } } },
  --     vsplit = { enter = true },
  --   },
  --   health = { checker = false },
  -- },
}
