return {
  {
    "henriklovhaug/Preview.nvim",
    ft = "markdown",
    cmd = "Preview",
    keys = { { "<leader>mp", "<cmd>Preview<CR>", desc = "[m]arkdown [p]review" } },
    config = true,
  },
  { "ellisonleao/glow.nvim", ft = "markdown", cmd = "Glow", config = { border = "single" } },
  {
    "epwalsh/obsidian.nvim",
    version = "*",
    ft = "markdown",
    opts = {
      workspaces = { { name = "notes", path = "~/notes" }, { name = "LGR", path = "~/notes/LGR" } },
      completion = { nvim_cmp = true, min_chars = 2 },
      preferred_link_style = "markdown",
      disable_frontmatter = true,
      picker = { name = "telescope.nvim", mappings = { new = "<C-x>", insert_link = "<C-l>" } },
      sort_by = "path",
      sort_reversed = false,
      ui = {
        enable = true,
        update_debounce = 200,
        checkboxes = {
          [" "] = { char = "󰄱", hl_group = "ObsidianTodo" },
          ["x"] = { char = "", hl_group = "ObsidianDone" },
          [">"] = { char = "", hl_group = "ObsidianRightArrow" },
          ["~"] = { char = "󰰱", hl_group = "ObsidianTilde" },
        },
        bullets = { char = "•", hl_group = "ObsidianBullet" },
        external_link_icon = { char = "", hl_group = "ObsidianExtLinkIcon" },
        reference_text = { hl_group = "ObsidianRefText" },
        highlight_text = { hl_group = "ObsidianHighlightText" },
        tags = { hl_group = "ObsidianTag" },
        block_ids = { hl_group = "ObsidianBlockID" },
      },
    },
  },
}
