return {
  "stevearc/oil.nvim",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  opts = {
    default_file_explorer = true,
    columns = { "icon" },
    buf_options = { buflisted = false, bufhidden = "hide" },
    win_options = { list = true },
    delete_to_trash = false,
    skip_confirm_for_simple_edits = false,
    prompt_save_on_select_new_entry = true,
    cleanup_delay_ms = 2000,
    lsp_rename_autosave = true,
    constrain_cursor = "name", -- bool / name / editable
    use_default_keymaps = false,
    keymaps = {
      ["?"] = "actions.show_help",
      ["~"] = "actions.open_cwd",
      ["@"] = "actions.cd",
      ["gs"] = "actions.change_sort",
      ["gx"] = "actions.open_external",
      ["g."] = "actions.toggle_hidden",
      ["g\\"] = "actions.toggle_trash",
      ["h"] = "actions.parent",
      ["l"] = "actions.select",
      ["<CR>"] = "actions.select",
      ["<C-v>"] = "actions.select_vsplit",
      ["<C-x>"] = "actions.select_split",
      ["<C-t>"] = "actions.select_tab",
      ["<C-p>"] = "actions.preview",
      ["<C-f>"] = "actions.preview_scroll_down",
      ["<C-b>"] = "actions.preview_scroll_up",
      ["<C-c>"] = "actions.close",
      ["<C-r>"] = "actions.refresh",
    },
    view_options = { show_hidden = true, is_hidden_file = function(name, _) return vim.startswith(name, ".") end },
    float = {
      padding = 4,
      max_width = math.floor(vim.api.nvim_win_get_width(0) * 0.4),
      max_height = math.floor(vim.api.nvim_win_get_height(0) * 0.4),
      override = function(conf)
        conf.style = "minimal"
        return conf
      end,
    },
    -- preview = {
    --   -- max_width = 0.5,
    --   -- min_width = 0.2,
    --   -- width = nil,
    --   -- max_height = 0.8,
    --   -- min_height = 0.4,
    --   -- height = nil,
    --   border = "rounded",
    --   win_options = { winblend = 0 },
    --   update_on_cursor_moved = true,
    -- },
    -- progress = {
    --   max_width = 0.6,
    --   min_width = 0.3,
    --   width = nil,
    --   max_height = 0.4,
    --   min_height = 0.2,
    --   height = nil,
    --   border = "rounded",
    --   minimized_border = "none",
    --   win_options = { winblend = 0 },
    -- },
  },
}
