return {
  "stevearc/oil.nvim",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  opts = {
    default_file_explorer = true,
    columns = { "icon" },
    buf_options = { buflisted = false, bufhidden = "hide" },
    win_options = {
      wrap = false,
      signcolumn = "no",
      cursorcolumn = false,
      foldcolumn = "0",
      spell = false,
      list = true,
      conceallevel = 3,
      concealcursor = "nvic",
    },
    delete_to_trash = false,
    skip_confirm_for_simple_edits = false,
    prompt_save_on_select_new_entry = true,
    cleanup_delay_ms = 2000,
    lsp_rename_autosave = true, -- unmodified / bool
    constrain_cursor = "name", -- bool / name / editable
    keymaps = {
      ["?"] = "actions.show_help",
      ["<CR>"] = "actions.select",
      ["<C-v>"] = "actions.select_vsplit",
      ["<C-x>"] = "actions.select_split",
      ["<C-t>"] = "actions.select_tab",
      ["<C-p>"] = "actions.preview",
      ["<C-b>"] = "actions.preview_scroll_up",
      ["<C-f>"] = "actions.preview_scroll_down",
      ["<C-c>"] = "actions.close",
      ["<C-r>"] = "actions.refresh",
      ["-"] = "actions.parent",
      ["_"] = "actions.open_cwd",
      ["@"] = "actions.cd",
      ["~"] = "actions.tcd",
      ["gs"] = "actions.change_sort",
      ["gx"] = "actions.open_external",
      ["g."] = "actions.toggle_hidden",
      ["g\\"] = "actions.toggle_trash",
    },
    use_default_keymaps = false,
    view_options = {
      show_hidden = true,
      is_hidden_file = function(name, _) return vim.startswith(name, ".") end,
      is_always_hidden = function() return false end,
      sort = { { "type", "asc" }, { "name", "asc" } },
    },
    float = {
      padding = 4,
      max_width = 0,
      max_height = 0,
      border = "rounded",
      win_options = { winblend = 0 },
      override = function(conf) return conf end,
    },
    preview = {
      max_width = 0.5,
      min_width = 0.2,
      width = nil,
      max_height = 0.8,
      min_height = 0.4,
      height = nil,
      border = "rounded",
      win_options = { winblend = 0 },
      update_on_cursor_moved = true,
    },
    progress = {
      max_width = 0.6,
      min_width = 0.3,
      width = nil,
      max_height = 0.4,
      min_height = 0.2,
      height = nil,
      border = "rounded",
      minimized_border = "none",
      win_options = { winblend = 0 },
    },
  },
}
