import = [ "~/.config/alacritty/colors/Oxocarbon.toml" ]
shell = { program = "/usr/bin/fish", args = ["-c", "zellij attach home"] }
#working_directory = ""
live_config_reload = true
#ipc_socket = true

[env]
CURRENT_TERM = "alacritty"

[window]
dimensions                = { columns = 0, lines = 0 }
position                  = "None"
padding                   = { x = 0, y = 0 }
dynamic_padding           = true
decorations               = "None"
opacity                   = 0.9
startup_mode              = "Windowed"
title                     = "Alacritty"
dynamic_title             = false
class                     = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"
resize_increments         = false

[scrolling]
history    = 4000
#multiplier = 3

[font]
normal              = { family = "Iosevka Nerd Font Mono", style = "Regular" }
bold                = { family = "Iosevka Nerd Font Mono", style = "Heavy" }
italic              = { family = "Iosevka Nerd Font Mono", style = "Light" }
bold_italic         = { family = "Iosevka Nerd Font Mono", style = "BoldItalic" }
size                = 16.0
offset              = { x = 0, y = 0 }
glyph_offset        = { x = 0, y = 0 }
builtin_box_drawing = true

[cursor]
style = { shape = "Block", blinking = "Off" }
vi_mode_style = "None"
#blink_interval = 0
#blink_timeout = 0
unfocused_hollow = true
#thickness = 0.15

[colors]
draw_bold_text_with_bright_colors = true
