require("core.functions")
F.DisableBuiltin()
require("core.options")
require("core.keymaps")
require("util.objects")
if vim.g.neovide then require("core.neovide") end
local Tim = require("lazyTim")
require("lazy").setup("plugins", Tim)
require("core.autocmds")
vim.cmd.colorscheme("kanagawa")
