---GRIM.static provides a collection of static resources.
---@class GRIM.static
---@field border_simple string[]
---@field border [string[]]
---@field icon table
---@field root_markers [string[]]
---@field treesitter_grammars string[]

---@type GRIM.static
return {
  border_simple = { "┌", "─", "┐", "│", "┘", "─", "└", "│" },
  border = {
    { "┌", "Normal" },
    { "─", "Normal" },
    { "┐", "Normal" },
    { "│", "Normal" },
    { "┘", "Normal" },
    { "─", "Normal" },
    { "└", "Normal" },
    { "│", "Normal" },
  },
  icon = {
    mode = "",
    normal = "",
    visual = "",
    insert = "",
    command = "",
    git = {
      branch = "",
      add = " ",
      add_simple = "⁺ ",
      change = "󰝤 ",
      change_simple = "∼ ",
      change_simple_up = "° ",
      del = " ",
      del_simple = "⁻ ",
    },
    diagnostics = {
      error = " ",
      error_empty = " ",
      error_simple = "× ",
      error_ascii = "e ",
      warn = " ",
      warn_empty = " ",
      warn_ascii = "w ",
      info = " ",
      info_empty = "󰋽 ",
      info_ascii = "i ",
      hint = "󰌵 ",
      hint_empty = " ",
      hint_ascii = "h ",
    },
    ui = {
      angle_down_s = "",
      angle_left_l = "",
      angle_left_s = "",
      angle_left_x = "❮",
      angle_right_l = "",
      angle_right_s = "",
      angle_right_x = "❯",
      angle_up_s = "",
      arrow_down = "↓",
      arrow_left = "←",
      arrow_right = "→",
      arrow_up = "↑",
      box_check = "",
      box_empty = "󰄱",
      box_full = "󰝤",
      check = "󰄬",
      check_circle = "",
      circle_circle = "",
      circle_circle_l = "◉",
      circle_full = "●",
      circle_outline = "○",
      circle_right = "",
      circle_x = "󰰱",
      clock = "󰥔",
      cross = "󰅖",
      diamond = "◆",
      dot = "",
      dot_l = "•",
      dot_s = "·",
      ellipsis = "…",
      exclamation = "",
      link = "",
      lock = "",
      space = "␣",
      triangle_right_s = "",
      separator_statusline = "│",
      whirl = "⌘",
    },
    kind_icons = {
      Text = "󰉿",
      Method = "󰊕",
      Function = "󰊕",
      Constructor = "󰒓",
      Field = "󰜢",
      Variable = "󰆦",
      Property = "󰖷",
      Class = "󱡠",
      Interface = "󱡠",
      Struct = "󱡠",
      Module = "󰅩",
      Unit = "󰪚",
      Value = "󰦨",
      Enum = "󰦨",
      EnumMember = "󰦨",
      Keyword = "󰻾",
      Constant = "󰏿",
      Snippet = "󱄽",
      Color = "󰏘",
      File = "󰈔",
      Reference = "󰬲",
      Folder = "󰉋",
      Event = "󱐋",
      Operator = "󰪚",
      TypeParameter = "󰬛",
    },
  },
  root_markers = {
    -- [Lua]
    {
      ".emmyrc.json",
      ".luacheckrc",
      ".luarc.json",
      ".luarc.jsonc",
      ".stylua.toml",
      "lazy-lock.json",
    },
    -- [OCaml]
    {
      "dune-project",
      "dune-workspace",
      ".ocamlformat",
      ".ocp-indent",
      "*.opam",
      ".opam",
      "*.dune",
      "*.ml",
      "*.mli",
    },
    -- [Haskell]
    {
      "*.cabal",
      "cabal.project",
      "cabal.project.local",
      "hie.yaml",
      "stack.yaml",
      "package.yaml",
      "package.yaml.lock",
      "*.hs",
    },
    -- [Go]
    {
      "main.go",
      "build.go",
      "go.mod",
      "go.work",
      "go.sum",
      "*.go",
    },
    -- [Rust]
    {
      "Cargo.toml",
      "Cargo.lock",
      "mod.rs",
      "rust-analyzer.json",
      "rust-project.json",
      "package.json",
    },
    -- [Python]
    {
      "__init__.py",
      ".ruff.toml",
      "ruff.toml",
      "ty.toml",
      "pyproject.toml",
      ".pyproject.toml",
      "setup.py",
      "setup.cfg",
      "requirements.txt",
      "pyrightconfig.json",
      "Pipfile",
    },
    -- [sh]
    { ".shellcheckrc", "shellcheckrc" },
    -- [Fish]
    { "config.fish", "conf.d", "*.fish" },
    -- [C/C++]
    {
      ".ccls",
      "compile_commands.json",
      "compile_flags.txt",
      ".clangd",
      ".clang-tidy",
      ".clang-format",
      "*.cmake",
      "cmake*/",
      "CMakePresets.json",
      "CTestConfig.cmake",
    },
    -- [JS/TS]
    {
      "tsconfig.json",
      "jsconfig.json",
      "biome.json",
      "biome.jsonc",
      "package-lock.json",
      "yarn.lock",
      "pnpm-lock.yaml",
      "bun.lockdb",
      "bun.lock",
      "deno.lock",
    },
    -- [Generic]
    {
      "meson.build",
      "meson_options.txt",
      "*.ini",
      "*.conf",
      "*.json",
      "config",
      "config.ini",
      "config.toml",
      "config.conf",
      "config.json",
      "settings.ini",
      "settings.toml",
      "settings.conf",
      "settings.json",
      "configure.ac",
      "configure.sh",
      ".editorconfig",
      "Makefile",
      "MakeFile",
      "makefile",
      "MAKEFILE",
      "TODO",
      "TODO.md",
      "TODO.org",
      "README",
      "README.md",
      "README.org",
      "README.txt",
      "README.pdf",
      "license",
      "LICENSE",
      "*.org",
      ".git/",
      ".gitignore",
      "src/",
      "bin/",
      "lib/",
      "test/",
      "build/",
      "_build/",
      "scripts/",
      "out/",
      "assets/",
      "static/",
      "app/",
    },
  },
  treesitter_grammars = {
    "gitcommit",
    "gitignore",
    "git_config",
    "git_rebase",
    "regex",
    "bash",
    "fish",
    "c",
    "cpp",
    "ocaml",
    "ocaml_interface",
    "menhir",
    "haskell",
    "python",
    "rust",
    "go",
    "gomod",
    "gosum",
    "lua",
    "luadoc",
    "markdown",
    "markdown_inline",
    "vim",
    "vimdoc",
    "javascript",
    "typescript",
    "hyprlang",
    "hurl",
    "json",
    "jq",
    "ini",
    "toml",
    "yaml",
    "html",
    "http",
  },
}
