S = {}

S.BorderSimple = { "┌", "─", "┐", "│", "┘", "─", "└", "│" }

S.Border = {
  { "┌", "Normal" },
  { "─", "Normal" },
  { "┐", "Normal" },
  { "│", "Normal" },
  { "┘", "Normal" },
  { "─", "Normal" },
  { "└", "Normal" },
  { "│", "Normal" },
}

S.VimModeLowercaseFull = {
  ["n"] = "normal",
  ["no"] = "normal",
  ["nov"] = "normal",
  ["noV"] = "normal",
  ["no\22"] = "normal",
  ["niI"] = "normal",
  ["niR"] = "normal",
  ["niV"] = "normal",
  ["nt"] = "normal",
  ["ntT"] = "normal",
  ["v"] = "visual",
  ["vs"] = "visual",
  ["V"] = "visual",
  ["Vs"] = "visual",
  ["\22"] = "visual",
  ["\22s"] = "visual",
  ["s"] = "select",
  ["S"] = "select",
  ["\19"] = "insert",
  ["i"] = "insert",
  ["ic"] = "insert",
  ["ix"] = "insert",
  ["R"] = "replace",
  ["Rc"] = "replace",
  ["Rx"] = "replace",
  ["Rv"] = "replace",
  ["Rvc"] = "replace",
  ["Rvx"] = "replace",
  ["c"] = "command",
  ["cv"] = "command",
  ["ce"] = "command",
  ["r"] = "...",
  ["rm"] = "M",
  ["r?"] = "?",
  ["!"] = "󰩌",
  ["t"] = "terminal",
}

S.VimModeTwo = {
  ["n"] = "NO",
  ["no"] = "OP",
  ["nov"] = "OC",
  ["noV"] = "OL",
  ["no\x16"] = "OB",
  ["\x16"] = "VB",
  ["niI"] = "IN",
  ["niR"] = "RE",
  ["niV"] = "RV",
  ["nt"] = "NT",
  ["ntT"] = "TM",
  ["v"] = "VI",
  ["vs"] = "VI",
  ["V"] = "VL",
  ["Vs"] = "VL",
  ["\x16s"] = "VB",
  ["s"] = "SE",
  ["S"] = "SL",
  ["\x13"] = "SB",
  ["i"] = "IN",
  ["ic"] = "IC",
  ["ix"] = "IX",
  ["R"] = "RE",
  ["Rc"] = "RC",
  ["Rx"] = "RX",
  ["Rv"] = "RV",
  ["Rvc"] = "RC",
  ["Rvx"] = "RX",
  ["c"] = "CO",
  ["cv"] = "CV",
  ["r"] = "PR",
  ["rm"] = "PM",
  ["r?"] = "P?",
  ["!"] = "SH",
  ["t"] = "TE",
}

S.Icons = {
  mode = "",
  normal = "",
  visual = "",
  insert = "",
  command = "",
  git = {
    branch = "",
    added = " ",
    added_simple = "⁺ ",
    modified = "󰝤 ",
    modified_simple = "∼ ",
    modified_simple_up = "° ",
    removed = " ",
    removed_simple = "⁻ ",
  },
  diagnostics = {
    error = " ",
    error_simple = "×",
    warn = " ",
    info = " ",
    hint = "󰌵 ",
    hintfull = " ",
  },
  ui = {
    box_full = "󰝤",
    box_empty = "󰄱",
    box_check = "",
    circle_right = "",
    circle_x = "󰰱",
    circle_full = "●",
    circle_outline = "○",
    circle_circle = "",
    circle_circle_l = "◉",
    dot_l = "•",
    dot = "",
    dot_s = "·",
    lock = "",
    link = "",
    clock = "󰥔",
    angle_right_l = "",
    angle_left_l = "",
    angle_right_x = "❯",
    angle_left_x = "❮",
    angle_down_s = "",
    angle_left_s = "",
    angle_right_s = "",
    angle_up_s = "",
    arrow_down = "↓",
    arrow_left = "←",
    arrow_right = "→",
    arrow_up = "↑",
    cross = "󰅖",
    check = "󰄬",
    diamond = "◆",
    triangle_right_s = "",
    ellipsis = "…",
    space = "␣",
  },
  kind_icons = {
    Text = "󰉿",
    Method = "󰊕",
    Function = "󰊕",
    Constructor = "󰒓",
    Field = "󰜢",
    Variable = "󰆦",
    Property = "󰖷",
    Class = "󱡠",
    Interface = "󱡠",
    Struct = "󱡠",
    Module = "󰅩",
    Unit = "󰪚",
    Value = "󰦨",
    Enum = "󰦨",
    EnumMember = "󰦨",
    Keyword = "󰻾",
    Constant = "󰏿",
    Snippet = "󱄽",
    Color = "󰏘",
    File = "󰈔",
    Reference = "󰬲",
    Folder = "󰉋",
    Event = "󱐋",
    Operator = "󰪚",
    TypeParameter = "󰬛",
  },
}

S.root_markers = {
  -- [Lua]
  ".emmyrc.json",
  ".luacheckrc",
  ".luarc.json",
  ".luarc.jsonc",
  ".stylua.toml",
  "lazy-lock.json",
  -- [OCaml]
  -- "dune",
  "dune-project",
  "dune-workspace",
  ".ocamlformat",
  ".ocp-indent",
  "*.opam",
  ".opam",
  -- [Haskell]
  "*.cabal",
  "cabal.project",
  "cabal.project.local",
  "hie.yaml",
  "stack.yaml",
  "package.yaml",
  "package.yaml.lock",
  -- [GO]
  "main.go",
  "build.go",
  "go.mod",
  "go.work",
  "go.sum",
  -- [C|C++] (Clangd|CCLS)
  ".ccls",
  "compile_commands.json",
  "compile_flags.txt",
  ".clangd",
  ".clang-tidy",
  ".clang-format",
  -- [Python]
  "__init__.py",
  ".ruff.toml",
  "ruff.toml",
  "pyproject.toml",
  ".pyproject.toml",
  "setup.py",
  "setup.cfg",
  "requirements.txt",
  -- [Rust]
  "Cargo.toml",
  "Cargo.lock",
  "mod.rs",
  "rust-project.json",
  "package.json",
  -- [Generic]
  "*.ini",
  "*.conf",
  "*.json",
  "config",
  "config.ini",
  "config.toml",
  "config.conf",
  "config.json",
  "settings.ini",
  "settings.toml",
  "settings.conf",
  "settings.json",
  ".editorconfig",
  "Makefile",
  "MakeFile",
  "makefile",
  "MAKEFILE",
  "TODO",
  "TODO.md",
  "README",
  "README.md",
  "README.org",
  "README.txt",
  "README.pdf",
  "license",
  "LICENSE",
  ".git/",
  ".gitignore",
  "src/",
  "bin/",
  "lib/",
  "test/",
  "build/",
  "_build/",
  "scripts/",
  "out/",
  "assets/",
  "static/",
  "app/",
}

S.FtSpecial = {
  "help",
  "qf",
  "git",
  "fugitive",
  "NeogitStatus",
  "lazy",
  "mason",
  "checkhealth",
}

S.FtIgnore = {
  "oil",
  "noice",
  "help",
  "qf",
  "checkhealth",
}

S.TSEnsure = {
  "gitcommit",
  "gitignore",
  "git_config",
  "git_rebase",
  "regex",
  "bash",
  "fish",
  "c",
  "cpp",
  "ocaml",
  "ocaml_interface",
  "menhir",
  "haskell",
  "python",
  "rust",
  "go",
  "gomod",
  "gosum",
  "lua",
  "luadoc",
  "markdown",
  "markdown_inline",
  "vim",
  "vimdoc",
  "javascript",
  "typescript",
  "hyprlang",
  "hurl",
  "json",
  "jq",
  "ini",
  "toml",
  "yaml",
  "html",
  "http",
}

return S
