(deftheme doom-plain-dark
  "Theme inspired by gko's plain dark.")

(custom-theme-set-variables
 'doom-plain-dark
 '(ansi-color-names-vector ["#222222" "#d7d5d1" "#d7d5d1" "#d7d5d1" "#d7d5d1" "#d7d5d1" "#d7d5d1" "#d7d5d1"])
 '(rustic-ansi-faces ["#222222" "#d7d5d1" "#d7d5d1" "#d7d5d1" "#d7d5d1" "#d7d5d1" "#d7d5d1" "#d7d5d1"])
 '(exwm-floating-border-color "#d7d5d1")
 '(fci-rule-color "#545053")
 '(jdee-db-spec-breakpoint-face-colors '("#838083" . "#d7d5d1"))
 '(jdee-db-requested-breakpoint-face-colors '("#838083" . "#d7d5d1"))
 '(jdee-db-active-breakpoint-face-colors '("#838083" . "#bbbbbb")))

(custom-theme-set-faces
 'doom-plain-dark
 '(bold ((((class color) (min-colors 257)) (:weight bold :foreground unspecified)) (((class color) (min-colors 256)) (:weight bold :foreground unspecified)) (((class color) (min-colors 16)) (:weight bold :foreground unspecified))))
 '(bold-italic ((t (:inherit (bold italic)))))
 '(italic ((t (:slant italic))))
 '(escape-glyph ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(fringe ((((class color) (min-colors 257)) (:inherit default :foreground "#202020")) (((class color) (min-colors 256)) (:inherit default :foreground nil)) (((class color) (min-colors 16)) (:inherit default :foreground nil))))
 '(region ((((class color) (min-colors 257)) (:background "#0e0c0a" :distant-foreground "#acaaa7" :extend t)) (((class color) (min-colors 256)) (:background nil :distant-foreground nil :extend t)) (((class color) (min-colors 16)) (:background nil :distant-foreground nil :extend t))))
 '(highlight ((((class color) (min-colors 257)) (:background "#bbbbbb" :foreground "#838083" :distant-foreground "#050505")) (((class color) (min-colors 256)) (:background nil :foreground nil :distant-foreground nil)) (((class color) (min-colors 16)) (:background nil :foreground nil :distant-foreground nil))))
 '(cursor ((((class color) (min-colors 257)) (:background "#bbbbbb")) (((class color) (min-colors 256)) (:background nil)) (((class color) (min-colors 16)) (:background nil))))
 '(shadow ((((class color) (min-colors 257)) (:foreground "#545053")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(minibuffer-prompt ((((class color) (min-colors 257)) (:foreground "#bbbbbb")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(tooltip ((((class color) (min-colors 257)) (:background "#434343" :foreground "#d7d5d1")) (((class color) (min-colors 256)) (:background nil :foreground nil)) (((class color) (min-colors 16)) (:background nil :foreground nil))))
 '(secondary-selection ((((class color) (min-colors 257)) (:background "#d7d5d1" :extend t)) (((class color) (min-colors 256)) (:background nil :extend t)) (((class color) (min-colors 16)) (:background nil :extend t))))
 '(lazy-highlight ((((class color) (min-colors 257) (background dark)) (:background "#828282" :foreground "#050505" :distant-foreground "#838083" :weight bold)) (((class color) (min-colors 256) (background dark)) (:background nil :foreground nil :distant-foreground nil :weight bold)) (((class color) (min-colors 16) (background dark)) (:background nil :foreground nil :distant-foreground nil :weight bold)) (((class color) (min-colors 257) (background light)) (:background "#4f4f4f" :foreground "#838083" :distant-foreground "#050505")) (((class color) (min-colors 256) (background light)) (:background nil :foreground nil :distant-foreground nil)) (((class color) (min-colors 16) (background light)) (:background nil :foreground nil :distant-foreground nil))))
 '(match ((((class color) (min-colors 257)) (:foreground "#d7d5d1" :background "#838083" :weight bold)) (((class color) (min-colors 256)) (:foreground nil :background nil :weight bold)) (((class color) (min-colors 16)) (:foreground nil :background nil :weight bold))))
 '(trailing-whitespace ((((class color) (min-colors 257)) (:background "#d7d5d1")) (((class color) (min-colors 256)) (:background nil)) (((class color) (min-colors 16)) (:background nil))))
 '(nobreak-space ((t (:inherit escape-glyph :underline t))))
 '(vertical-border ((((class color) (min-colors 257)) (:background "#d7d5d1" :foreground "#d7d5d1")) (((class color) (min-colors 256)) (:background nil :foreground nil)) (((class color) (min-colors 16)) (:background nil :foreground nil))))
 '(link ((((class color) (min-colors 257)) (:foreground "#bbbbbb" :underline t :weight bold)) (((class color) (min-colors 256)) (:foreground nil :underline t :weight bold)) (((class color) (min-colors 16)) (:foreground nil :underline t :weight bold))))
 '(error ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(warning ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(success ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(font-lock-builtin-face ((((class color) (min-colors 257)) (:foreground "#838083")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(font-lock-comment-face ((((class color) (min-colors 257)) (:foreground "#545053" :slant italic)) (((class color) (min-colors 256)) (:foreground nil :slant italic)) (((class color) (min-colors 16)) (:foreground nil :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-doc-face ((((class color) (min-colors 257)) (:inherit font-lock-comment-face :foreground "#545053")) (((class color) (min-colors 256)) (:inherit font-lock-comment-face :foreground nil)) (((class color) (min-colors 16)) (:inherit font-lock-comment-face :foreground nil))))
 '(font-lock-constant-face ((((class color) (min-colors 257)) (:foreground "#838083" :slant italic)) (((class color) (min-colors 256)) (:foreground nil :slant italic)) (((class color) (min-colors 16)) (:foreground nil :slant italic))))
 '(font-lock-function-name-face ((((class color) (min-colors 257)) (:foreground "#d7d5d1" :slant italic)) (((class color) (min-colors 256)) (:foreground nil :slant italic)) (((class color) (min-colors 16)) (:foreground nil :slant italic))))
 '(font-lock-keyword-face ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(font-lock-string-face ((((class color) (min-colors 257)) (:foreground "#838083")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(font-lock-type-face ((((class color) (min-colors 257)) (:foreground "#d7d5d1" :slant italic)) (((class color) (min-colors 256)) (:foreground nil :slant italic)) (((class color) (min-colors 16)) (:foreground nil :slant italic))))
 '(font-lock-variable-name-face ((((class color) (min-colors 257)) (:foreground "#838083")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(font-lock-number-face ((((class color) (min-colors 257)) (:foreground "#838083")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(font-lock-warning-face ((t (:inherit warning))))
 '(font-lock-negation-char-face ((((class color) (min-colors 257)) (:inherit bold :foreground "#d7d5d1")) (((class color) (min-colors 256)) (:inherit bold :foreground nil)) (((class color) (min-colors 16)) (:inherit bold :foreground nil))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 257)) (:inherit bold :foreground "#d7d5d1")) (((class color) (min-colors 256)) (:inherit bold :foreground nil)) (((class color) (min-colors 16)) (:inherit bold :foreground nil))))
 '(font-lock-preprocessor-char-face ((((class color) (min-colors 257)) (:inherit bold :foreground "#d7d5d1")) (((class color) (min-colors 256)) (:inherit bold :foreground nil)) (((class color) (min-colors 16)) (:inherit bold :foreground nil))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 257)) (:inherit bold :foreground "#d7d5d1")) (((class color) (min-colors 256)) (:inherit bold :foreground nil)) (((class color) (min-colors 16)) (:inherit bold :foreground nil))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 257)) (:inherit bold :foreground "#d7d5d1")) (((class color) (min-colors 256)) (:inherit bold :foreground nil)) (((class color) (min-colors 16)) (:inherit bold :foreground nil))))
 '(mode-line ((((class color) (min-colors 257)) (:background "#383838" :foreground unspecified :box (:line-width 8 :color "#383838"))) (((class color) (min-colors 256)) (:background nil :foreground unspecified :box (:line-width 8 :color nil))) (((class color) (min-colors 16)) (:background nil :foreground unspecified :box (:line-width 8 :color nil)))))
 '(mode-line-active ((t (:inherit mode-line))))
 '(mode-line-inactive ((((class color) (min-colors 257)) (:background "#323232" :foreground "#6f6f6f" :box (:line-width 8 :color "#323232"))) (((class color) (min-colors 256)) (:background nil :foreground nil :box (:line-width 8 :color nil))) (((class color) (min-colors 16)) (:background nil :foreground nil :box (:line-width 8 :color nil)))))
 '(mode-line-emphasis ((((class color) (min-colors 257)) (:foreground "#bbbbbb")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(mode-line-highlight ((((class color) (min-colors 257)) (:inherit highlight :distant-foreground "#222222")) (((class color) (min-colors 256)) (:inherit highlight :distant-foreground nil)) (((class color) (min-colors 16)) (:inherit highlight :distant-foreground nil))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(header-line ((t (:inherit mode-line))))
 '(header-line-highlight ((t (:inherit mode-line-highlight))))
 '(tab-line ((((class color) (min-colors 257)) (:background "#434343" :foreground "#434343" :box nil)) (((class color) (min-colors 256)) (:background nil :foreground nil :box nil)) (((class color) (min-colors 16)) (:background nil :foreground nil :box nil))))
 '(tab-line-tab ((((class color) (min-colors 257)) (:background "#222222" :foreground "#d7d5d1" :box nil)) (((class color) (min-colors 256)) (:background nil :foreground nil :box nil)) (((class color) (min-colors 16)) (:background nil :foreground nil :box nil))))
 '(tab-line-tab-inactive ((((class color) (min-colors 257)) (:inherit tab-line-tab :background "#434343" :foreground "#e7e5e3" :box nil)) (((class color) (min-colors 256)) (:inherit tab-line-tab :background nil :foreground nil :box nil)) (((class color) (min-colors 16)) (:inherit tab-line-tab :background nil :foreground nil :box nil))))
 '(tab-line-tab-inactive-alternate ((t (:inherit tab-line-tab-inactive))))
 '(tab-line-tab-current ((((class color) (min-colors 257)) (:background "#222222" :foreground "#d7d5d1")) (((class color) (min-colors 256)) (:background nil :foreground nil)) (((class color) (min-colors 16)) (:background nil :foreground nil))))
 '(tab-line-highlight ((t (:inherit tab-line-tab))))
 '(tab-line-close-highlight ((((class color) (min-colors 257)) (:foreground "#bbbbbb")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(line-number ((((class color) (min-colors 257)) (:inherit default :foreground "#444444" :distant-foreground unspecified :weight normal :italic unspecified :underline unspecified :strike-through unspecified)) (((class color) (min-colors 256)) (:inherit default :foreground nil :distant-foreground unspecified :weight normal :italic unspecified :underline unspecified :strike-through unspecified)) (((class color) (min-colors 16)) (:inherit default :foreground nil :distant-foreground unspecified :weight normal :italic unspecified :underline unspecified :strike-through unspecified))))
 '(line-number-current-line ((((class color) (min-colors 257)) (:inherit (hl-line default) :foreground "#bbbbbb" :distant-foreground unspecified :weight normal :italic unspecified :underline unspecified :strike-through unspecified)) (((class color) (min-colors 256)) (:inherit (hl-line default) :foreground nil :distant-foreground unspecified :weight normal :italic unspecified :underline unspecified :strike-through unspecified)) (((class color) (min-colors 16)) (:inherit (hl-line default) :foreground nil :distant-foreground unspecified :weight normal :italic unspecified :underline unspecified :strike-through unspecified))))
 '(agda2-highlight-keyword-face ((t (:inherit font-lock-keyword-face))))
 '(agda2-highlight-string-face ((t (:inherit font-lock-string-face))))
 '(agda2-highlight-number-face ((t (:inherit font-lock-string-face))))
 '(agda2-highlight-symbol-face ((t (:inherit font-lock-variable-name-face))))
 '(agda2-highlight-primitive-type-face ((t (:inherit font-lock-type-face))))
 '(agda2-highlight-bound-variable-face ((t (:inherit font-lock-variable-name-face))))
 '(agda2-highlight-inductive-constructor-face ((t (:inherit font-lock-type-face))))
 '(agda2-highlight-coinductive-constructor-face ((t (:inherit font-lock-type-face))))
 '(agda2-highlight-datatype-face ((t (:inherit font-lock-type-face))))
 '(agda2-highlight-field-face ((t (:inherit font-lock-type-face))))
 '(agda2-highlight-function-face ((t (:inherit font-lock-function-name-face))))
 '(agda2-highlight-module-face ((t (:inherit font-lock-variable-name-face))))
 '(agda2-highlight-postulate-face ((t (:inherit font-lock-type-face))))
 '(agda2-highlight-primitive-face ((t (:inherit font-lock-type-face))))
 '(agda2-highlight-macro-face ((t (:inherit font-lock-function-name-face))))
 '(agda2-highlight-record-face ((t (:inherit font-lock-type-face))))
 '(agda2-highlight-error-face ((t (:inherit font-lock-warning-face))))
 '(agda2-highlight-dotted-face ((t (:inherit font-lock-variable-name-face))))
 '(agda2-highlight-unsolved-meta-face ((t (:inherit font-lock-warning-face))))
 '(agda2-highlight-unsolved-constraint-face ((t (:inherit font-lock-warning-face))))
 '(agda2-highlight-termination-problem-face ((t (:inherit font-lock-warning-face))))
 '(agda2-highlight-positivity-problem-face ((t (:inherit font-lock-warning-face))))
 '(agda2-highlight-incomplete-pattern-face ((t (:inherit font-lock-warning-face))))
 '(agda2-highlight-typechecks-face ((t (:inherit font-lock-warning-face))))
 '(font-latex-bold-face ((t (:inherit bold))))
 '(font-latex-italic-face ((t (:inherit italic))))
 '(font-latex-math-face ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(font-latex-sedate-face ((t (:inherit font-lock-keyword-face))))
 '(font-latex-sectioning-0-face ((((class color) (min-colors 257)) (:foreground "#d7d5d1" :weight ultra-bold)) (((class color) (min-colors 256)) (:foreground nil :weight ultra-bold)) (((class color) (min-colors 16)) (:foreground nil :weight ultra-bold))))
 '(font-latex-sectioning-1-face ((((class color) (min-colors 257)) (:foreground "#d7d5d1" :weight semi-bold)) (((class color) (min-colors 256)) (:foreground nil :weight semi-bold)) (((class color) (min-colors 16)) (:foreground nil :weight semi-bold))))
 '(font-latex-sectioning-2-face ((((class color) (min-colors 257)) (:foreground "#d7d5d1" :weight semi-bold)) (((class color) (min-colors 256)) (:foreground nil :weight semi-bold)) (((class color) (min-colors 16)) (:foreground nil :weight semi-bold))))
 '(font-latex-sectioning-3-face ((((class color) (min-colors 257)) (:foreground "#e3e1de" :weight semi-bold)) (((class color) (min-colors 256)) (:foreground nil :weight semi-bold)) (((class color) (min-colors 16)) (:foreground nil :weight semi-bold))))
 '(font-latex-sectioning-4-face ((((class color) (min-colors 257)) (:foreground "#e3e1de" :weight semi-bold)) (((class color) (min-colors 256)) (:foreground nil :weight semi-bold)) (((class color) (min-colors 16)) (:foreground nil :weight semi-bold))))
 '(font-latex-sectioning-5-face ((((class color) (min-colors 257)) (:foreground "#e3e1de" :weight semi-bold)) (((class color) (min-colors 256)) (:foreground nil :weight semi-bold)) (((class color) (min-colors 16)) (:foreground nil :weight semi-bold))))
 '(font-latex-script-char-face ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(font-latex-string-face ((t (:inherit font-lock-string-face))))
 '(font-latex-warning-face ((t (:inherit font-lock-warning-face))))
 '(font-latex-verbatim-face ((((class color) (min-colors 257)) (:inherit fixed-pitch :foreground "#d7d5d1" :slant italic)) (((class color) (min-colors 256)) (:inherit fixed-pitch :foreground nil :slant italic)) (((class color) (min-colors 16)) (:inherit fixed-pitch :foreground nil :slant italic))))
 '(TeX-error-description-error ((t (:inherit error :weight bold))))
 '(TeX-error-description-warning ((t (:inherit warning :weight bold))))
 '(TeX-error-description-tex-said ((t (:inherit success :weight bold))))
 '(alert-high-face ((((class color) (min-colors 257)) (:inherit t :foreground "#d7d5d1")) (((class color) (min-colors 256)) (:inherit t :foreground nil)) (((class color) (min-colors 16)) (:inherit t :foreground nil))))
 '(alert-low-face ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(alert-moderate-face ((((class color) (min-colors 257)) (:inherit t :foreground "#e7e5e3")) (((class color) (min-colors 256)) (:inherit t :foreground nil)) (((class color) (min-colors 16)) (:inherit t :foreground nil))))
 '(alert-trivial-face ((((class color) (min-colors 257)) (:foreground "#545053")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(alert-urgent-face ((((class color) (min-colors 257)) (:inherit t :foreground "#d7d5d1")) (((class color) (min-colors 256)) (:inherit t :foreground nil)) (((class color) (min-colors 16)) (:inherit t :foreground nil))))
 '(all-the-icons-blue ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-blue-alt ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-cyan ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-cyan-alt ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-dblue ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-dcyan ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-dgreen ((((class color) (min-colors 257)) (:foreground "#969592")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-dmaroon ((((class color) (min-colors 257)) (:foreground "#969592")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-dorange ((((class color) (min-colors 257)) (:foreground "#969592")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-dpink ((((class color) (min-colors 257)) (:foreground "#dddbd7")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-dpurple ((((class color) (min-colors 257)) (:foreground "#969592")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-dred ((((class color) (min-colors 257)) (:foreground "#969592")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-dsilver ((((class color) (min-colors 257)) (:foreground "#dbd9d5")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-dyellow ((((class color) (min-colors 257)) (:foreground "#969592")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-green ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-lblue ((((class color) (min-colors 257)) (:foreground "#e3e1de")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-lcyan ((((class color) (min-colors 257)) (:foreground "#e3e1de")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-lgreen ((((class color) (min-colors 257)) (:foreground "#e3e1de")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-lmaroon ((((class color) (min-colors 257)) (:foreground "#e3e1de")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-lorange ((((class color) (min-colors 257)) (:foreground "#e3e1de")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-lpink ((((class color) (min-colors 257)) (:foreground "#edecea")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-lpurple ((((class color) (min-colors 257)) (:foreground "#e3e1de")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-lred ((((class color) (min-colors 257)) (:foreground "#e3e1de")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-lsilver ((((class color) (min-colors 257)) (:foreground "#f3f2f1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-lyellow ((((class color) (min-colors 257)) (:foreground "#e3e1de")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-maroon ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-orange ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-pink ((((class color) (min-colors 257)) (:foreground "#e5e3e1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-purple ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-purple-alt ((((class color) (min-colors 257)) (:foreground "#d7d4d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-red ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-red-alt ((((class color) (min-colors 257)) (:foreground "#d7d4d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-silver ((((class color) (min-colors 257)) (:foreground "#e9e7e5")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-yellow ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(all-the-icons-dired-dir-face ((((class color) (min-colors 257)) (:foreground "#545053")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(annotate-annotation ((((class color) (min-colors 257)) (:background "#313131" :foreground "#545053")) (((class color) (min-colors 256)) (:background nil :foreground nil)) (((class color) (min-colors 16)) (:background nil :foreground nil))))
 '(annotate-annotation-secondary ((((class color) (min-colors 257)) (:background "#343333" :foreground "#545053")) (((class color) (min-colors 256)) (:background nil :foreground nil)) (((class color) (min-colors 16)) (:background nil :foreground nil))))
 '(annotate-highlight ((((class color) (min-colors 257)) (:background "#313131" :underline "#bbbbbb")) (((class color) (min-colors 256)) (:background nil :underline nil)) (((class color) (min-colors 16)) (:background nil :underline nil))))
 '(annotate-highlight-secondary ((((class color) (min-colors 257)) (:background "#343333" :underline "#d7d5d1")) (((class color) (min-colors 256)) (:background nil :underline nil)) (((class color) (min-colors 16)) (:background nil :underline nil))))
 '(ansi-color-black ((((class color) (min-colors 257)) (:foreground "#222222" :background "#222222")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(ansi-color-red ((((class color) (min-colors 257)) (:foreground "#d7d5d1" :background "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(ansi-color-green ((((class color) (min-colors 257)) (:foreground "#d7d5d1" :background "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(ansi-color-yellow ((((class color) (min-colors 257)) (:foreground "#d7d5d1" :background "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(ansi-color-blue ((((class color) (min-colors 257)) (:foreground "#d7d5d1" :background "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(ansi-color-magenta ((((class color) (min-colors 257)) (:foreground "#d7d5d1" :background "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(ansi-color-cyan ((((class color) (min-colors 257)) (:foreground "#d7d5d1" :background "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(ansi-color-white ((((class color) (min-colors 257)) (:foreground "#d7d5d1" :background "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(ansi-color-bright-black ((((class color) (min-colors 257) (background light)) (:foreground "#202020" :background "#202020")) (((class color) (min-colors 256) (background light)) (:foreground nil :background nil)) (((class color) (min-colors 16) (background light)) (:foreground nil :background nil)) (((class color) (min-colors 257) (background dark)) (:foreground "#050505" :background "#050505")) (((class color) (min-colors 256) (background dark)) (:foreground nil :background nil)) (((class color) (min-colors 16) (background dark)) (:foreground nil :background nil))))
 '(ansi-color-bright-red ((((class color) (min-colors 257)) (:foreground "#dddbd7" :background "#dddbd7")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(ansi-color-bright-green ((((class color) (min-colors 257)) (:foreground "#dddbd7" :background "#dddbd7")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(ansi-color-bright-yellow ((((class color) (min-colors 257)) (:foreground "#dddbd7" :background "#dddbd7")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(ansi-color-bright-blue ((((class color) (min-colors 257)) (:foreground "#dddbd7" :background "#dddbd7")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(ansi-color-bright-magenta ((((class color) (min-colors 257)) (:foreground "#dddbd7" :background "#dddbd7")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(ansi-color-bright-cyan ((((class color) (min-colors 257)) (:foreground "#dddbd7" :background "#dddbd7")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(ansi-color-bright-white ((((class color) (min-colors 257)) (:foreground "#050505" :background "#050505")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(anzu-replace-highlight ((((class color) (min-colors 257)) (:background "#838083" :foreground "#d7d5d1" :weight bold :strike-through t)) (((class color) (min-colors 256)) (:background nil :foreground nil :weight bold :strike-through t)) (((class color) (min-colors 16)) (:background nil :foreground nil :weight bold :strike-through t))))
 '(anzu-replace-to ((((class color) (min-colors 257)) (:background "#838083" :foreground "#d7d5d1" :weight bold)) (((class color) (min-colors 256)) (:background nil :foreground nil :weight bold)) (((class color) (min-colors 16)) (:background nil :foreground nil :weight bold))))
 '(avy-background-face ((((class color) (min-colors 257)) (:foreground "#545053")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(avy-lead-face ((((class color) (min-colors 257)) (:background "#bbbbbb" :foreground "#222222" :distant-foreground "#d7d5d1" :weight bold)) (((class color) (min-colors 256)) (:background nil :foreground nil :distant-foreground nil :weight bold)) (((class color) (min-colors 16)) (:background nil :foreground nil :distant-foreground nil :weight bold))))
 '(avy-lead-face-0 ((((class color) (min-colors 257) (background dark)) (:inherit avy-lead-face :background "#cfcfcf")) (((class color) (min-colors 256) (background dark)) (:inherit avy-lead-face :background nil)) (((class color) (min-colors 16) (background dark)) (:inherit avy-lead-face :background nil)) (((class color) (min-colors 257) (background light)) (:inherit avy-lead-face :background "#828282")) (((class color) (min-colors 256) (background light)) (:inherit avy-lead-face :background nil)) (((class color) (min-colors 16) (background light)) (:inherit avy-lead-face :background nil))))
 '(avy-lead-face-1 ((((class color) (min-colors 257) (background dark)) (:inherit avy-lead-face :background "#e3e3e3")) (((class color) (min-colors 256) (background dark)) (:inherit avy-lead-face :background nil)) (((class color) (min-colors 16) (background dark)) (:inherit avy-lead-face :background nil)) (((class color) (min-colors 257) (background light)) (:inherit avy-lead-face :background "#4a4a4a")) (((class color) (min-colors 256) (background light)) (:inherit avy-lead-face :background nil)) (((class color) (min-colors 16) (background light)) (:inherit avy-lead-face :background nil))))
 '(avy-lead-face-2 ((((class color) (min-colors 257) (background dark)) (:inherit avy-lead-face :background "#f8f8f8")) (((class color) (min-colors 256) (background dark)) (:inherit avy-lead-face :background nil)) (((class color) (min-colors 16) (background dark)) (:inherit avy-lead-face :background nil)) (((class color) (min-colors 257) (background light)) (:inherit avy-lead-face :background "#121212")) (((class color) (min-colors 256) (background light)) (:inherit avy-lead-face :background nil)) (((class color) (min-colors 16) (background light)) (:inherit avy-lead-face :background nil))))
 '(bookmark-face ((((class color) (min-colors 257)) (:background "#313131" :extend t)) (((class color) (min-colors 256)) (:background nil :extend t)) (((class color) (min-colors 16)) (:background nil :extend t))))
 '(bmkp-*-mark ((((class color) (min-colors 257)) (:foreground "#222222" :background "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(bmkp->-mark ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(bmkp-D-mark ((((class color) (min-colors 257)) (:foreground "#222222" :background "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(bmkp-X-mark ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(bmkp-a-mark ((((class color) (min-colors 257)) (:background "#d7d5d1")) (((class color) (min-colors 256)) (:background nil)) (((class color) (min-colors 16)) (:background nil))))
 '(bmkp-bad-bookmark ((((class color) (min-colors 257)) (:foreground "#222222" :background "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(bmkp-bookmark-file ((((class color) (min-colors 257)) (:foreground "#d7d5d1" :background "#434343")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(bmkp-bookmark-list ((((class color) (min-colors 257)) (:background "#434343")) (((class color) (min-colors 256)) (:background nil)) (((class color) (min-colors 16)) (:background nil))))
 '(bmkp-buffer ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(bmkp-desktop ((((class color) (min-colors 257)) (:foreground "#222222" :background "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(bmkp-file-handler ((((class color) (min-colors 257)) (:background "#d7d5d1")) (((class color) (min-colors 256)) (:background nil)) (((class color) (min-colors 16)) (:background nil))))
 '(bmkp-function ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(bmkp-gnus ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(bmkp-heading ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(bmkp-info ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(bmkp-light-autonamed ((((class color) (min-colors 257)) (:foreground "#434343" :background "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(bmkp-light-autonamed-region ((((class color) (min-colors 257)) (:foreground "#434343" :background "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(bmkp-light-fringe-autonamed ((((class color) (min-colors 257)) (:foreground "#434343" :background "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(bmkp-light-fringe-non-autonamed ((((class color) (min-colors 257)) (:foreground "#434343" :background "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(bmkp-light-mark ((((class color) (min-colors 257)) (:foreground "#222222" :background "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(bmkp-light-non-autonamed ((((class color) (min-colors 257)) (:foreground "#222222" :background "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(bmkp-light-non-autonamed-region ((((class color) (min-colors 257)) (:foreground "#222222" :background "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(bmkp-local-directory ((((class color) (min-colors 257)) (:foreground "#222222" :background "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil :background nil)) (((class color) (min-colors 16)) (:foreground nil :background nil))))
 '(bmkp-local-file-with-region ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(bmkp-local-file-without-region ((((class color) (min-colors 257)) (:foreground "#545053")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(bmkp-man ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(bmkp-no-jump ((((class color) (min-colors 257)) (:foreground "#545053")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(bmkp-no-local ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(bmkp-non-file ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(bmkp-remote-file ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(bmkp-sequence ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(bmkp-su-or-sudo ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(bmkp-t-mark ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(bmkp-url ((((class color) (min-colors 257)) (:foreground "#d7d5d1" :underline t)) (((class color) (min-colors 256)) (:foreground nil :underline t)) (((class color) (min-colors 16)) (:foreground nil :underline t))))
 '(bmkp-variable-list ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(cfw:face-title ((((class color) (min-colors 257)) (:foreground "#d7d5d1" :weight bold :height 2.0 :inherit variable-pitch)) (((class color) (min-colors 256)) (:foreground nil :weight bold :height 2.0 :inherit variable-pitch)) (((class color) (min-colors 16)) (:foreground nil :weight bold :height 2.0 :inherit variable-pitch))))
 '(cfw:face-header ((((class color) (min-colors 257)) (:foreground "#b2b1ae" :weight bold)) (((class color) (min-colors 256)) (:foreground nil :weight bold)) (((class color) (min-colors 16)) (:foreground nil :weight bold))))
 '(cfw:face-sunday ((((class color) (min-colors 257)) (:foreground "#b2b1ae" :weight bold)) (((class color) (min-colors 256)) (:foreground nil :weight bold)) (((class color) (min-colors 16)) (:foreground nil :weight bold))))
 '(cfw:face-saturday ((((class color) (min-colors 257)) (:foreground "#b2b1ae" :weight bold)) (((class color) (min-colors 256)) (:foreground nil :weight bold)) (((class color) (min-colors 16)) (:foreground nil :weight bold))))
 '(cfw:face-holiday ((((class color) (min-colors 257)) (:background "#434343" :weight bold)) (((class color) (min-colors 256)) (:background nil :weight bold)) (((class color) (min-colors 16)) (:background nil :weight bold))))
 '(cfw:face-grid ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(cfw:face-periods ((((class color) (min-colors 257)) (:foreground "#d7d5d1")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
